### ISSUE TITLE
选择器改名，原有规则就不在列表里面

### ISSUE THREAD

**Issue by myselfghost** [sumory/orange#110]
orange  先建了一个选择器，在这个选择器下面建了规则，然后修改选择器的名称，然后同步配置，这个选择器下面的规则就不在列表里面了。

**Comment by sumory** [comment]
无法复现，请提交具体case、数据或操作步骤

**Comment by sumory** [comment]
我用最新的代码和新配置复现出来了，我查查具体原因后fix

**Comment by sumory** [comment]
fixed with commit [#888852](https://github.com/sumory/orange/commit/88885257a670b4a83c472ba12ee48d701fa2e21f)
