### ISSUE TITLE
只启用重定向插件，按案例配置跳转一直提示upstream not found

### ISSUE THREAD

**Issue by sayid** [sumory/orange#111]
选择器我使用的全流量，规则使用的案例。
一直提示这个：
404! upstream not found. Host: 192.168.5.217  URI: /to_baidu

这个提示应该是分流代理插件提示的吧，但是分流插件已经关掉了。
请问应该如何解决呢？

**Comment by sayid** [comment]
另外还要咨询一下，插件的选择器是否全局的？

**Comment by sumory** [comment]
1）关于404提示

```
404! upstream not found. Host: 192.168.5.217 URI: /to_baidu
```
这个提示和分流插件没关系，你的应用中没有`/to_baidu`这个URL的实现，当然会报这个错误。这个错误是默认配置在`nginx.conf`里的default_upstream返回的，它的代码如下：

```nginx
# default upstream server
    server {
        listen 8001;
        server_name localhost 127.0.0.1;
        access_log ./logs/default_upstream_access.log main;
        error_log ./logs/default_upstream_error.log;

        location / {
            content_by_lua_block {
                ngx.status = 404
                ngx.say([[404! upstream not found. Host: ]] .. ngx.var.host .. "  URI: " .. ngx.var.uri)
            }
        }
    }
```

请熟悉下Nginx的基本配置就能看懂了。

2）插件

> 插件的选择器是否全局的？

不理解你这个疑问是什么意思。如果配置了“全局”选择器，那么只要经过这个插件的流量都会经过这个选择器。

如果你对Nginx/OpenResty的请求处理过程不熟悉，建议先查下相关方面的资料，有些疑问自然迎刃而解。

**Comment by sayid** [comment]
我是只在URL重定向插件中定义了/to_baidu就跳转到百度

**Comment by sumory** [comment]
你什么都没配就能调到百度？就只配了/to_baidu？如果是请清除浏览器缓存或换用其他浏览器，之前重定向可能会被缓存住。

**Comment by sayid** [comment]
`# main server
    server {
        listen       80;
        #server_name  my_domain.com;

        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }

        location / {
            set $upstream_host $host;
            set $upstream_url 'http://default_upstream';

            rewrite_by_lua_block {
                local orange = context.orange
                orange.redirect()
                orange.rewrite()
            }

            access_by_lua_block {
                local orange = context.orange
                orange.access()
            }

            # proxy
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Scheme $scheme;
            proxy_set_header Host $upstream_host;
            proxy_pass $upstream_url;


            header_filter_by_lua_block {
                local orange = context.orange
                orange.header_filter()
            }

            body_filter_by_lua_block {
                local orange = context.orange
                orange.body_filter()
            }

            log_by_lua_block {
location /robots.txt {
            return 200 'User-agent: *\nDisallow: /';
        }
    }

    # default upstream server
    server {
        listen 8001;
        server_name localhost 127.0.0.1;
        access_log ./logs/default_upstream_access.log main;
        error_log ./logs/default_upstream_error.log;

        location / {
            content_by_lua_block {
                ngx.status = 404
                ngx.say([[404! upstream not found. Host: ]] .. ngx.var.host .. "  URI: " .. ngx.var.uri)
            }
        }
    }`


我试了原来要用80端口，不是8001，之后就可以重定向了。但是做分流代理API分发还是有问题，上面是我的配置文件，麻烦您看下 有问题吗？

**Comment by sayid** [comment]
`{
  "divide.enable": true,
  "divide.selector.a1ae87f7-e338-42ac-82c8-ede297a3f8af.rules": [
    {
      "id": "de57feb4-4608-4218-95bd-071976bb1ea2",
      "log": true,
      "name": "用户中心规则",
      "upstream_host": "http://192.168.5.215:7071",
      "upstream_url": "http://192.168.5.215:7071/account/v3/list",
      "judge": {
        "type": 0,
        "conditions": [
          {
            "value": "/account/v3/list",
            "operator": "=",
            "type": "URI"
          }
        ]
      },
      "enable": true,
      "time": "2017-05-17 13:31:46",
      "extractor": {
        "extractions": [],
        "type": 2
      }
    }
  ],
  "divide.selectors": {
    "a1ae87f7-e338-42ac-82c8-ede297a3f8af": {
      "time": "2017-05-17 13:24:13",
      "enable": true,
      "type": 0,
      "id": "a1ae87f7-e338-42ac-82c8-ede297a3f8af",
      "judge": [],
      "name": "用户中心",
      "handle": {
        "continue": false,
        "log": false
      },
      "rules": [
        "de57feb4-4608-4218-95bd-071976bb1ea2"
      ]
    }
  },
  "divide.meta": {
    "selectors": [
      "a1ae87f7-e338-42ac-82c8-ede297a3f8af"
    ]
  }
}`

以上是分流规则，提示400 Bad Request

**Comment by sayid** [comment]
`{
  "divide.enable": true,
  "divide.selector.a1ae87f7-e338-42ac-82c8-ede297a3f8af.rules": [
    {
      "id": "de57feb4-4608-4218-95bd-071976bb1ea2",
      "log": true,
      "name": "用户中心规则",
      "upstream_host": "http://192.168.5.215:7071",
      "upstream_url": "http://192.168.5.215:7071/account/v3/list",
      "judge": {
        "type": 0,
        "conditions": [
          {
            "value": "/account/v3/list",
            "operator": "=",
            "type": "URI"
          }
        ]
      },
      "enable": true,
      "time": "2017-05-17 13:31:46",
      "extractor": {
        "extractions": [],
        "type": 2
      }
    }
  ],
  "divide.selectors": {
    "a1ae87f7-e338-42ac-82c8-ede297a3f8af": {
      "time": "2017-05-17 13:24:13",
      "enable": true,
      "type": 0,
      "id": "a1ae87f7-e338-42ac-82c8-ede297a3f8af",
      "judge": [],
      "name": "用户中心",
      "handle": {
        "continue": false,
        "log": false
      },
      "rules": [
        "de57feb4-4608-4218-95bd-071976bb1ea2"
      ]
    }
  },
  "divide.meta": {
    "selectors": [
      "a1ae87f7-e338-42ac-82c8-ede297a3f8af"
    ]
  }
}`
以上是分流规则，提示400 Bad Request

**Comment by sayid** [comment]
已经可以了，谢谢

**Comment by sayid** [comment]
我的意思是每个插件都要新建选择器，每个插件之间的选择器是否可以复用、通用

**Comment by noname007** [comment]
理清api,新搞一套ui,抽象一层，就可以不用修改后端、实现你想要的了。

不过从功能上来说。两者没有区别。
