### ISSUE TITLE
Signatur auth能否使用OpenSSL不对称密钥做签名验证

### ISSUE THREAD

**Issue by sayid** [sumory/orange#112]
Signatur auth能否使用OpenSSL不对称密钥做签名验证，例如jwt。让orange能够解析jwt数据。

我们想在签名中或者令牌中隐藏服务调用人的开发者id/uuid，在根据开发者id/uuid做诸如限流等等规则配置

**Comment by noname007** [comment]
你这是两个问题，jwt + 限流

jwt 想法不错，可以搞。这个插件先前搞得有点烂，只用了md5.

限流利用其它插件做。

但是目前的orange 条件表达式，还识别不出来jwt。如果能识别出来，就很容易在插件级别搞定这事，不然插件要费点事。

**Comment by sumory** [comment]
可以在header头里种一个标志，表明这是带jwt的请求
