### ISSUE TITLE
dashboard session timeout

### ISSUE THREAD

**Issue by marlondu** [sumory/orange#113]
dashboard auth 设为true之后，每隔一两分钟session就失效了，就得重新登陆一次。
我看代码里默认的是3600秒啊。
你们测试的时候有这问题吗

**Comment by noname007** [comment]
我也有这个问题。但是忘记怎么回事了。。。。

**Comment by sumory** [comment]
lua_code_cache设为on了么? 
另一个可能的原因是orange使用了lor的默认session插件，可能有些场景下会有bug.

**Comment by marlondu** [comment]
lua_code_cache设为on了

**Comment by sumory** [comment]
如果遇到这个问题，可以升级lor到v0.3.2+版本

**Comment by marlondu** [comment]
我是使用opm方式安装的lor, 现在还是0.3.1版本，能处理一下吗，谢谢。

**Comment by marlondu** [comment]
我用脚本方式安装后，lord -v 可以正常输出，但是还是找不到lor模块。
lua entry thread aborted: runtime error: ./dashboard/server.lua:3: module 'lor.lib.middleware.session' not found
