### ISSUE TITLE
请问自定义插件文档什么时候补充上呢？

### ISSUE THREAD

**Issue by sayid** [sumory/orange#115]
我们的业务场景需要使用kong的消费者模块和针对消费者的auth认证，想在orange上扩展。
请问什么时候会有自定义插件文档呢？

**Comment by sumory** [comment]
最快月底吧

**Comment by noname007** [comment]
我感觉你可以参考下这个插件的开发，orange 整个系统结构封装的很好，插件开发很简单。

https://github.com/sumory/orange/pull/71

**Comment by sumory** [comment]
@linger1216 写过两篇Orange相关的代码和架构解读文档，有一篇详细介绍了Orange插件的代码和运行机制，建议参考：https://github.com/linger1216/understanding-orange
