### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by jik1992** [sumory/orange#12]
1.install success openresty/luajit ,ln -s nginx , and ln -s luajit
2.install lor 
2.user by root
sh start.sh , show error

2016/06/20 23:24:26 [error] 7939#0: [lua] config_loader.lua:21: load(): Load config file from ./orange.conf
2016/06/20 23:24:26 [error] 7939#0: [lua] file_store.lua:16: new(): load file store configurations... ./data.json

:)    thx

**Comment by sumory** [comment]
```
2016/06/20 23:24:26 [error] 7939#0: [lua] config_loader.lua:21: load(): Load config file from ./orange.conf
2016/06/20 23:24:26 [error] 7939#0: [lua] file_store.lua:16: new(): load file store configurations... ./data.json
```
these two lines are not errors.
this is just the "ngx.ERR" level log.
