### ISSUE TITLE
针对选择器的流程顺序问题

### ISSUE THREAD

**Issue by numen06** [sumory/orange#123]
##### 需求或场景

对于结构添加权限之后才能进入下一个过滤器
例如我要访问/doc/*下面的API接口
本来/doc是内部架构，现在需要开放出去那么通过Orange开放认证之后才能转发到内网的/doc接口

##### 使用的插件

URL Redirect
HTTP Basic Auth

##### 具体的配置

那么在URL Redirect设置一个url转发，从oranger的8888转发到内网的/doc
同样在HTTP Basic Auth也设置一个相融的拦截/doc认证

##### 期望的结果

正常来说应该先需要认证但前提结构，然后再进入相应的内网结构
官方应该出一个标准的选择器流程，或者让用户自由的配置选择器的先后顺序
现在看来所有的结果都违背顺序的，包括防火墙的顺序

##### 错误的结果

如果两个插件同时配置相同的路径，那么Orange会先转发，而不是先认证，单独开哪个一个都可以正常运行，同时运行的时候是错的。

**Comment by sumory** [comment]
你说的这个场景，按你的想法是需要以下两个插件
URL Redirect
HTTP Basic Auth

**Comment by sumory** [comment]
按你的想法，你这个场景使用了两个插件:
```
URL Redirect
HTTP Basic Auth
```
这两个插件的执行顺序是根据它们在Nginx执行阶段中的顺序来确定的，这并不是Orange指定的顺序。

其次，我感觉你这个需求应该用`HTTP Basic Auth`和`divide`插件，选择器通过`HTTP Basic Auth`先过虑是否访问合法，如果合法的话在该过滤器内再配置规则让它通过Divide插件打到后端的`/doc`服务。

你这个场景使用URL Redirect并不合适，请注意Nginx里的`redirect`语义和用法。
