### ISSUE TITLE
by_lua_block 代码块适配哪些地方？

### ISSUE THREAD

**Issue by coagent** [sumory/orange#125]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景

1. 有多个域名，即多 server { xxxx }，每个 server 下有多个 API 接口(location)。
2. 我们想针对不同的 location 进行代理分流。

##### 使用的插件

针对这个需求你使用了哪个或哪几个插件

1. divide
2. monitor

##### 具体的配置

1. divide 插件：匹配 host(server_name)，然后过滤 header，针对不同的 header 指定不同的 upstream。
2. monitor 插件：匹配 host(server_name) + uri(localtion) 进行自定义监控。

##### 疑问

1. 以下代码块需要在各个 location 下插入吗？还是在 location / { ... } 里放一份，其他 location /xxxx/, location /yyyy/, location /zzzz/ 会自动继承？

```
rewrite_by_lua_block {
    local orange = context.orange
    orange.redirect()
    orange.rewrite()
}

access_by_lua_block {
    local orange = context.orange
    orange.access()
}

header_filter_by_lua_block {
    local orange = context.orange
    orange.header_filter()
}

body_filter_by_lua_block {
    local orange = context.orange
    orange.body_filter()
}

log_by_lua_block {
    local orange = context.orange
    orange.log()
}
```
2. 有没有结合动态 upstream 的插件进行分流的例子？

##### 错误的结果

描述实际的结果， 比如错误的输出或截图

**Comment by sumory** [comment]
Orange目前不支持动态分流，请先在nginx.conf里配好upstream然后再使用divide插件。

**Comment by coagent** [comment]
感谢回复！

rewrite_by_lua_block 等 by_lua_block 代码块，需要在各个 location 下插入吗？还是在 location / { ... } 里放一份，其他 location /xxxx/, location /yyyy/, location /zzzz/ 会自动继承？

**Comment by sumory** [comment]
你是不是理解错了，你并不需要也不能修改目前Orange使用的*_by_lua_block块
