### ISSUE TITLE
可否根据IP限制访问速度

### ISSUE THREAD

**Issue by d-anz** [sumory/orange#126]
##### 需求或场景
根据ip来限制速度，例如一个ip一秒内只允许访问100次。这个ip不需要指定
##### 使用的插件
NginxHttpLimitReqModule

##### 具体的配置

 NginxHttpLimitReqModule可以根据条件进行请求频率的控制。例如可以定义以下代码：
 
  	
http {
limit_req_zone  $binary_remote_addr  zone=my_req_zone:10m   rate=1r/s;
...
server {
...
location /somedir/ {
limit_req_zone   zone= my_req_zone  burst=2;
}

##### 期望的结果

如题

##### 错误的结果

-

**Comment by noname007** [comment]
参看文档
http://orange.sumory.com/docs/api/property_rate_limiting/
