### ISSUE TITLE
分流插件: GET请求出现参数丢失问题

### ISSUE THREAD

**Issue by meyer-net** [sumory/orange#128]
##### 需求或场景

通过ORANGE，对内网多个分布式的子系统，实现请求分发
例如：
www.abc.com 是orange接受的站点
www.abc.com/jtrade 是对 内网 192.168.1.XXX:111 的访问
特在 代理&分流 模块，做如下配置的分流：
![image](https://user-images.githubusercontent.com/16422453/27470758-ec61dfdc-5827-11e7-9141-e3d6ea4ba7e5.png)

##### 使用的插件

代理&分流

##### 具体的配置

{
  "name": "特殊_",
  "judge": {
    "type": 0,
    "conditions": [
      {
        "type": "URI",
        "operator": "match",
        "value": "^/jtrade"
      }
    ]
  },
  "extractor": {
    "type": 1,
    "extractions": [
      {
        "type": "Query",
        "name": "transaction_id"
      },
      {
        "type": "Query",
        "name": "charset"
      },
      {
        "type": "Query",
        "name": "merchant_no"
      },
      {
        "type": "Query",
        "name": "sign"
      },
      {
        "type": "Query",
        "name": "out_transaction_id"
      },
      {
        "type": "Query",
        "name": "version"
      },
      {
        "type": "Query",
        "name": "out_trade_no"
      },
      {
        "type": "Query",
        "name": "service"
      },
      {
        "type": "Query",
        "name": "total_fee"
      },
      {
        "type": "Query",
        "name": "empty"
      },
      {
        "type": "Query",
        "name": "time_end"
      },
      {
        "type": "Query",
        "name": "sign_type"
      },
      {
        "type": "Query",
        "name": "acquirer_type"
      },
      {
        "type": "Query",
        "name": "status"
      },
      {
        "type": "Query",
        "name": "message"
      },
      {
        "type": "Query",
        "name": "currency"
      }
    ]
  },
  "upstream_host": "127.0.0.1",
  "upstream_url": "http://trade_upstream/?transaction_id=${1}&charset=${2}&merchant_no=${3}&sign=${4}&out_transaction_id=${5}&version=${6}&out_trade_no=${7}&service=${8}&total_fee=${9}&currency=${16}&time_end=${11}&sign_type=${12}&acquirer_type=${13}&status=${14}&message=${15}&empty=${10}",
  "log": true,
  "enable": true
}

##### 期望的结果

设置提取的变量，与所分流请求组装的upstream是对等的。

##### 错误的结果

无论下标为10的 empty 参数（或任意参数名），任何值，在下游程序中都只会请求成 empty=${10}。
![image](https://user-images.githubusercontent.com/16422453/27471084-16b65b4a-5829-11e7-88d9-6db9660b3087.png)

ORANGE仅有日志如下：
2017/06/23 15:08:09 [info] 7270#7270: *9 [lua] handler.lua:37: filter_rules(): [Divide-Match-Rule] 特殊_ host:127.0.0.1 uri:/jtrade, client: 127.0.0.1, server: 127.0.0.1, request: "POST /jtrade?transaction_id=1&charset=2&merchant_no=3&sign=4&out_transaction_id=5&message=6&version=7&out_trade_no=8&service=9&total_fee=10&currency=11&time_end=12&sign_type=13&acquirer_type=14&status=15 HTTP/1.1", host: "127.0.0.1"

**Comment by meyer-net** [comment]
接上述，原先因为分流器没法传递GET参数到后端。才引发此需求，后改成模板式提取变量，测试OK，运行两天后，数据出现MISSING，原因不明。

**Comment by meyer-net** [comment]
另，解决需求问题GET参数传递至下游时，需要改动/orange/plugins/divide/handler.lua:51插入代码。

`
                    local args = ngx.encode_args(ngx.req.get_uri_args())
                    if #args > 0 then
                        rule.upstream_url = rule.upstream_url.. '?' .. args
                    end
`

**Comment by sumory** [comment]
👍 下个版本会修复分流对GET请求的支持问题

**Comment by sumory** [comment]
我排查了一下现在分流插件是支持GET请求的，v0.6.4及之前版本的Orange，分以下两种情况：

1）当在dashboard上填写的`upstream url`类似于`http://test_upstream1`，即指定的字符串后面不带`/`时，是可以正常拿到GET参数、POST参数以及URI的
2）当在dashboard上填写的`upstream url`类似于`http://test_upstream1/`，即指定的字符串带`/`，既不能正常拿到GET参数也不能拿到URI，但POST参数能正常拿到

以上两种情况的区别本质上是Nginx的`proxy_pass`指令的行为。

**Comment by sumory** [comment]
其实你的问题我总结了下，并给出一个解决方案，组合使用rewrite和divide插件即可。

**需求如下**

最前端打过来的请求为`http://localhost:8000/first_rewrite_then_divide?a=1&b=2`，想要运行在后端8002端口的程序来处理，但后端使用的参数可能是`new_a=1&new_b=2`，需要在Orange里实现参数的变换并正确得将请求打到后端处理。

**Nginx配置**

假设我们的Nginx配置如下：
```
upstream test_upstream1 {
        server localhost:8002;
}

server {
        listen 8002;
        server_name localhost 127.0.0.1;

        location / {
            content_by_lua_block {
                local query = ngx.req.get_uri_args()
                local q = ngx.encode_args(query)
                -- 打印URI和参数，验证是否成功
                ngx.say([[test upstream 1 reached! Host: ]] .. ngx.var.host .. "  URI: " .. ngx.var.uri .. " QUERY:" .. q)
            }
        }
}
```


**解决方案**

先通过rewrite变换将原始请求rewire到一个新URI，比如`/test1`，并对原始请求参数做一下变换让它能适配后端的接口，使用URI重定向插件配置大概如下：
![image](https://user-images.githubusercontent.com/1326893/27759855-ee08569a-5e6c-11e7-9442-6c2532bf2825.png)
然后给这个新URI`/test1`配个分流指向后端真正的`test_upstream1`，使用分流插件配置如下：
![image](https://user-images.githubusercontent.com/1326893/27759859-091ff154-5e6d-11e7-9944-a75c8b2081b7.png)

**测试**

模拟一个请求`http://localhost:8000/first_rewrite_then_divide?a=1&b=2`, 查看结果发现输出如下：
![image](https://user-images.githubusercontent.com/1326893/27759905-ca8b2f48-5e6d-11e7-90df-ba43d98eb1ac.png)
也就是我们正确地使得请求转发到了后端并转换了参数。

**Comment by meyer-net** [comment]
该方案，转发，尝试了一下，不可行。也就是在多级目录下 /test_upstream1还是会使用到提取变量/test_upstream1${1}  依旧是没接收到数据。建议测试。

**Comment by sumory** [comment]
![image](https://user-images.githubusercontent.com/1326893/27762287-ec514016-5ea1-11e7-9acc-b966e51a2c4d.png)
都已经说过了，什么时候有参数什么时候无参数以及原因，请你仔细认真看！

**Comment by sumory** [comment]
另外，我费了半天劲给你写的**组合使用rewrite+divide**解决你问题的方法，是能work的！QQ上也已经讨论了很多。issue还有其他人看，所以不要随意发你并没有按解决思路准确测试的结论，避免误导其它人

**Comment by zhangzhipeng** [comment]
请提供一下示例www.abc.com 是orange接受的站点
www.abc.com/jtrade 是对 内网 192.168.1.1访问不带jtrade的，目前给出的rewrite+divide方案是依然带有有一个子路径test1
