### ISSUE TITLE
安装好orange后，全局监控里面没有任何数据

### ISSUE THREAD

**Issue by kasimi-rin** [sumory/orange#13]
按照文档安装好orange之后，全局监控里看不到一点数据。

启动nginx的时候有如下报错，不知道会不会有影响：
2016/06/20 23:24:26 [error] 7939#0: [lua] config_loader.lua:21: load(): Load config file from ./orange.conf
2016/06/20 23:24:26 [error] 7939#0: [lua] file_store.lua:16: new(): load file store configurations... ./data.json

**Comment by sumory** [comment]
- 没有数据是因为你都没有访问量
- 这不是错，这两条是以ngx.ERR级别打印的日志

**Comment by syhily** [comment]
这两条记录不算报错，而是某人非要用 ERR 打印日志的结果。
