### ISSUE TITLE
插件启动失败

### ISSUE THREAD

**Issue by bringtree** [sumory/orange#133]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景
能够启动插件，还有 怎么添加 接口。。。
描述你想实现的功能

##### 使用的插件
http://127.0.0.1:9999/redirect/enable
针对这个需求你使用了哪个或哪几个插件

##### 具体的配置
运行了 docker的那个 
在插件里做了什么配置， 可以截图， 一定要描述清楚你的配置

##### 期望的结果

按你选用的插件和所做的配置， 你期望的结果是什么？ 比如访问了哪个URL， 参数都是什么， 期望的输出是什么
{
    "success": true,
   能够启动插件
}
##### 错误的结果

{
    "success": false,
    "msg": "failed to disable plugin"
}

描述实际的结果， 比如错误的输出或截图

**Comment by bringtree** [comment]
只允许了程序 其他没有 进行任何操作 ，接下来 是要进行什么操作吗

**Comment by sumory** [comment]
首先确保你的MySQL连接什么的都成功了；然后有错误先查看error日志了打了什么出来

**Comment by bringtree** [comment]
@sumory 
`{
    "plugins": [
        "stat",
        "monitor",
        "redirect",
        "rewrite",
        "rate_limiting",
        "property_rate_limiting",
        "basic_auth",
        "key_auth",
        "signature_auth",
        "waf",
        "divide",
        "kvstore"
    ],
    "store": "mysql",
    "store_mysql": {
        "timeout": 5000,
        "connect_config": {
            "host": "127.0.0.1",
            "port": 3366,
            "database": "orange",
            "user": "root",
            "password": "root",
            "max_packet_size": 1048576
        },
        "pool_config": {
            "max_idle_timeout": 10000,
            "pool_size": 3
        },
        "desc": "mysql configuration"
    },
    "dashboard": {
        "auth": false,
        "session_secret": "y0ji4pdj61aaf3f11c2e65cd2263d3e7e5",
        "whitelist": [
            "^/auth/login$",
            "^/error/$"
        ]
    },
    "api": {
        "auth_enable": true,
        "credentials": [
            {
                "username":"api_username",
                "password":"api_password"
            }
        ]
    }
}`

外部的 MySQL localhost:3366 数据库是databse 密码账号都是root

**Comment by bringtree** [comment]
是连接不上
