### ISSUE TITLE
可以 增加 分流的 设置demo吗

### ISSUE THREAD

**Issue by bringtree** [sumory/orange#134]
要分流到192.168.0.1,192.168.0.2,192.168.0.3,192.168.0.4,192.168.0.5

**Comment by sumory** [comment]
请把issue写的简洁清晰，一坨字里面只有一行字是有效内容。。

**Comment by bringtree** [comment]
ok 改好了。不好意思。

**Comment by sumory** [comment]
这是我之前写的一个小例子：

1) 假设我们在nginx.conf里建了一个upstream，它的配置如下

```
#代理位于其他服务器的程序，这里以127.0.0.1:8001和127.0.0.1:8002为例
upstream my_upstream {
     server 127.0.0.1:8001;
     server 127.0.0.1:8002;
}
```

2) 确保`127.0.0.1:8001`和`127.0.0.1:8002`能提供`/abc`这个请求的处理，即访问`http://127.0.0.1:8001/abc` 时能正常提供服务

3) 在dashboard里`代理&分流插件`的配置如下：

配一个选择器和一条规则：

![image](https://user-images.githubusercontent.com/1326893/28348843-dfc78d04-6c71-11e7-9726-abb6b314f64b.png)

规则详情如下：

![image](https://user-images.githubusercontent.com/1326893/28348880-17f1a552-6c72-11e7-827e-9b5de864e54e.png)

4) 访问`http://${your_host}:${your_port}/abc`, 就会发现能正常访问后端实际的API，即`http://127.0.0.1:8001/abc`或`http://127.0.0.1:8002/abc`

**Comment by bringtree** [comment]
万分感谢。

**Comment by sumory** [comment]
分流插件的一些需要注意的问题：
https://github.com/sumory/orange/issues/128 分流插件: GET请求出现参数丢失问题
https://github.com/sumory/orange/issues/136 使用分流插件后获取post请求参数问题

**Comment by y3093** [comment]
你这东西就是有bug
