### ISSUE TITLE
使用mysql存储错误

### ISSUE THREAD

**Issue by chuckpu** [sumory/orange#14]
2016/07/06 12:44:09 [error] 19220#0: [lua] config_loader.lua:21: load(): Load config file from /opt/nginx/orange.conf
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_db.lua:35: query(): connected to mysql, reused_times:0 sql:select `key`, `value` from meta where `key` like "%.enable", context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_store.lua:48: query(): MySQLStore:query empty, sql:select `key`, `value` from meta where `key` like "%.enable", context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_db.lua:35: query(): connected to mysql, reused_times:1 sql:select `value` from monitor order by id asc, context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_store.lua:48: query(): MySQLStore:query empty, sql:select `value` from monitor order by id asc, context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_db.lua:35: query(): connected to mysql, reused_times:2 sql:select `value` from redirect order by id asc, context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_store.lua:48: query(): MySQLStore:query empty, sql:select `value` from redirect order by id asc, context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_db.lua:35: query(): connected to mysql, reused_times:3 sql:select `value` from rewrite order by id asc, context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_store.lua:48: query(): MySQLStore:query empty, sql:select `value` from rewrite order by id asc, context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_db.lua:35: query(): connected to mysql, reused_times:4 sql:select `value` from waf order by id asc, context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_store.lua:48: query(): MySQLStore:query empty, sql:select `value` from waf order by id asc, context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_db.lua:35: query(): connected to mysql, reused_times:5 sql:select `value` from divide order by id asc, context: ngx.timer
2016/07/06 12:44:09 [error] 19222#0: [lua] mysql_store.lua:48: query(): MySQLStore:query empty, sql:select `value` from divide order by id asc, context: ngx.timer

**Comment by sumory** [comment]
这不是错误，这是使用ngx.ERR级别打印的日志

**Comment by sumory** [comment]
已调整为将业务日志打印成INFO级别，明确的错误或者需要提醒用户的使用ERR级别打印.
