### ISSUE TITLE
IP 不是ngx.var.remote_addr的情况

### ISSUE THREAD

**Issue by myselfghost** [sumory/orange#140]
在实际生产环境中，我们对用户的标识，很可能不是 ngx.var.remote_addr，那么
condition_type == "IP" then
        real =  ngx.var.remote_addr

可能就不恰当。

**Comment by sumory** [comment]
实际环境中，IP字段的取值非常复杂，如果请求路径里经过了各种代理，这个字段就更多样。

所以建议应该在nginx.conf里自行配置，使得`ngx.var.remote_addr`字段符合直观正确语义。

参考：https://yq.aliyun.com/articles/68398

**Comment by noname007** [comment]
好文章啊，
