### ISSUE TITLE
默认用户登录出错

### ISSUE THREAD

**Issue by jetspeed** [sumory/orange#142]
配置为auth:false时，能正常进入dashboard页面。
配置为auth:true时，无法登录。

##### 错误的结果

使用默认的admin / orange_admin 用户登录，报
server.lua:59 
lor/lor/lor/lib/utils/aes.lua:47: attempt to index a nil value

**Comment by jetspeed** [comment]
我发现make install 到/usr/local是正常的。
但是我的服务器上没有root权限， openresty  lor  orange 都是加了prefix路径， 然后就出现这个错误了。

**Comment by sumory** [comment]
- make install时可以指定安装路径
- 如果不是安装到/usr/local, 下载orange后，把配置文件改好，直接使用`start.sh`启动即可，无需安装

**Comment by jetspeed** [comment]
似乎跟路径没关系， 我安装到/usr/local下，仍然是这个错误。

2017/08/26 08:58:04 [error] 23063#0: *7 [lua] session.lua:77: func(): cannot get session_data:no cookie found in the current    request, client: 125.34.186.45, server: , request: "POST /auth/login HTTP/1.1", host: "10*.170.*2.14*:9999", referrer: "http:// 10*.170.*2.14*:9999:9999/auth/login"
 2017/08/26 08:58:04 [info] 23063#0: *7 [lua] db.lua:35: query(): connected to mysql, reused_times:0 sql:select * from           dashboard_user where username='admin' and password='1fe832a7246fd19b7ea400a10d23d1894edfa3a5e09ee27e0c4a96eb0136763d', client:  125.34.186.45, server: , request: "POST /auth/login HTTP/1.1", host: "10*.170.*2.14*:9999", referrer: "http://10*.170.*2.14*:   9999/auth/login"
 2017/08/26 08:58:04 [info] 23063#0: *7 [lua] auth.lua:62: func(): 管理员[admin]登录, client: 125.34.186.45, server: , request:  "POST /auth/login HTTP/1.1", host: "10*.170.*2.14*:9999, referrer: "10*.170.*2.14*:9999/auth/login"
 2017/08/26 08:58:04 [error] 23063#0: *7 [lua] server.lua:59: func(): /usr/local/lor/lor/lib/utils/aes.lua:47: attempt to index  a nil value
stack traceback:
     /usr/local/lor/lor/lib/router/router.lua:204: in function '__index'
     /usr/local/lor/lor/lib/utils/aes.lua:47: in function 'encrypt'
     /usr/local/lor/lor/lib/middleware/session.lua:25: in function 'encode_data'
     /usr/local/lor/lor/lib/middleware/session.lua:101: in function 'set'
     ./dashboard/routes/auth.lua:68: in function 'func'
     /usr/local/lor/lor/lib/router/router.lua:192: in function </usr/local/lor/lor/lib/router/router.lua:191>
     [C]: in function 'xpcall'
     /usr/local/lor/lor/lib/router/router.lua:191: in function 'next'
     ./dashboard/middleware/check_is_admin.lua:38: in function 'func'
     /usr/local/lor/lor/lib/router/router.lua:192: in function </usr/local/lor/lor/lib/router/router.lua:191>
     [C]: in function 'xpcall'
     ...
     /usr/local/lor/lor/lib/middleware/session.lua:172: in function 'func'
     /usr/local/lor/lor/lib/router/router.lua:192: in function </usr/local/lor/lor/lib/router/router.lua:191>
     [C]: in function 'xpcall'
     /usr/local/lor/lor/lib/router/router.lua:191: in function 'next'
     /usr/local/lor/lor/lib/router/router.lua:213: in function 'handle'
     /usr/local/lor/lor/lib/application.lua:95: in function </usr/local/lor/lor/lib/application.lua:94>
     [C]: in function 'xpcall'
     /usr/local/lor/lor/lib/application.lua:94: in function 'handle'
     /usr/local/lor/lor/lib/application.lua:54: in function 'run'
     content_by_lua(nginx.conf:166):4: in function <content_by_lua(nginx.conf:166):1>, client: 125.34.186.45, server: ,          request: "POST /auth/login HTTP/1.1", 10*.170.*2.14*:9999", referrer: "http://10*.170.*2.14*:9999/auth/login"
 2017/08/26 08:58:42 [info] 23063#0: *7 client 125.34.186.45 closed keepalive connection

**Comment by jetspeed** [comment]
我将lor换成0.3.1，因为我看0.3.1之后对session的处理换成了中间件，但是也不行。
错误似乎是什么session取不到，跟我的浏览器设置有关系么？

**Comment by jetspeed** [comment]
用start.sh也不行。  我不设置auth为true的时候， 能进入使用， 说明我的安装是没有问题的。

**Comment by sumory** [comment]
lor升级到最新版0.3.3，orange也用最新版0.6.4试试。这个错误没人报过，我这边也没有复现出来，你再试试。

**Comment by jetspeed** [comment]
我确认 使用 openresty-1.11.2.5  最新代码库的lor  和 orange 会出现这个错误。

auth为false的时候，正常。

**Comment by jetspeed** [comment]
我查了一下， aes引用了openresty
8月17日更新的 openresty-1.11.2.5 有这个问题。他的changelog里有动过aes。

已确认使用 openresty-1.11.2.3   openresty-1.11.2.4 没有这个问题。
@sumory

**Comment by sumory** [comment]
👍 你看好改的话给提个兼容的fix？

**Comment by noname007** [comment]
pr is very welcom :)

**Comment by saighost** [comment]
本地遇到了同样的错误。。。
服务器是openresty/1.11.2.2 没这个问题

把session_secret改成少于8位就可以了。

ps:
ChangeLog of Version 1.11.2.5 - 17 August 2017
upgraded lua-resty-string to 0.10.
bugfix: resty.aes: fixed memory overrun bug when user provided a salt of less than 8 characters but EVP_BytesToKey() expects more. disallows salt strings longer than 8 characters to avoid false sense of security. thanks Datong Sun for the patch.

**Comment by sumory** [comment]
fixed with commit [#fc0d03](https://github.com/sumory/orange/commit/fc0d03edc073bb21746ea66832815778e13cbe5a). please check it with your env @jetspeed . thanks @saighost

**Comment by sumory** [comment]
[lor](https://github.com/sumory/lor) which is used by Orange is fixed with this commit [#c8c864](https://github.com/sumory/lor/commit/c8c864bb34e2fcdef8df1fb9b3a95c53a1130797)
