### ISSUE TITLE
 监控数据如何清空？

### ISSUE THREAD

**Issue by phphappy** [sumory/orange#144]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景
           监控数据如何清空？
描述你想实现的功能
          对自定义监控数据清零

**Comment by sumory** [comment]
请按要求提issue，最基本的，无用信息删掉！

**Comment by sumory** [comment]
监控数据现在保存在`monitor`这个shared dict中，因为只使用了几个key，内存占用非常少，所以并没有写清除数据的功能。

如果有这个需求，可以暴露一个http接口删除或重置这个shared dict里的相关key即可。

接口写法可参见kvstore这个插件相关处理: https://github.com/sumory/orange/blob/master/orange/plugins/kvstore/api.lua#L346

**Comment by phphappy** [comment]
非常感谢
