### ISSUE TITLE
resty.aes限制加盐长度小于8 charaters, orange的默认secret过长导致登陆失败

### ISSUE THREAD

**Issue by tpwow** [sumory/orange#148]
软件版本：
resty 0.19
nginx version: openresty/1.11.2.5

问题描述: orange.conf使用大于8 charaters的session_secret会导致登陆失败

原因;
resty.aes 增加了盐长度限制, 参考这里:https://github.com/openresty/lua-resty-string/commit/82ff0e3660305078f57a5986be27c530a2141def

**Comment by sumory** [comment]
Orange使用了lor来做dashboard，最新版的[lor](https://github.com/sumory/lor)已经fix这个问题，请升级
