### ISSUE TITLE
orange重写插件问题

### ISSUE THREAD

**Issue by phphappy** [sumory/orange#149]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景
public void WeChatLoginSM2(HttpServletRequest request, @RequestParam(value = "uuid", required = false) String uuid,
			@RequestParam(value = "code", required = false) String code, HttpServletResponse response)
	if (!redisService.exists("MY" + uuid)) {
			StringBuilder sb = new StringBuilder();
			sb = sb.append("<html>");
			sb.append("<head>");
			sb.append("<script type=\"text/javascript\"> window.location.href = \"" + pcUrl + "invalidation.html"
					+ "\";</script>");
			sb.append("</head>");
			sb.append("<body> ");
			sb.append("</body>");
			sb.append("</html>");
			String string1 = sb.toString();
			log.info("微信提示：二维码失效");
			response.getOutputStream().write(string1.getBytes());
    
}
描述你想实现的功能
    通过orange分流插件该接口，能够正常显示输出的网页
##### 使用的插件
分流插件
针对这个需求你使用了哪个或哪几个插件

##### 具体的配置

在插件里做了什么配置， 可以截图， 一定要描述清楚你的配置

##### 期望的结果
正常显示输出网页
按你选用的插件和所做的配置， 你期望的结果是什么？ 比如访问了哪个URL， 参数都是什么， 期望的输出是什么

##### 错误的结果
现在显示的是网页字符串<html><header><script type=\"text/javascript\"> window.location.href ="invalidation.html";</script></header></html>

**Comment by sumory** [comment]
不符合提问规范的issue不予处理并关闭
