### ISSUE TITLE
New restful URI variable extract directive

### ISSUE THREAD

**Issue by syhily** [sumory/orange#15]
It's unquestionable, given this issue for urging multiply variables extractor from a request URI, that it's leaving a lot to be desired.

Yet, as demonstrated by the wide range of different ideas on how it should be improved, it's hard to find consensus on what 'better' actually looks like. Having looked through the discussions in QQ group, there are two broad categories into which the concerns fall into: the first is adding dyadic array for all variable extractors and the second is adding features for new rest template directive.

Dyadic array would increase complexity for configuration and process. But this would be the best solution for URI variable regular matching searching and would support a max range of URI.

So a new custom `variable extract directives` is a niche requirement, and we want to focus our efforts on making apps a possibility so that it is possible to add a brand new directive suits your use-case for getting multiply variables for a URI, rather than modify old ones. Therefore this issue exists purely to address a new restful URI extractor and a new directive. As for me, I would like to name them as `Restful Template`.

Old variable extractor using `${number}` directive to identify expected variables. But `Restful Template` would using a new directive differ before. It is `{variable name}`.

There are two key things which makes this new directive quite desirable:

1. It matches our request uri by predefined placeholders, and would easily assemble them with old directive `${number}`.
2. It reduce the complexity comparing to dyadic array.

I would give some restrictions on what this `Restful Template` could and couldn't.

1. Every rewrite or redirect rule would only have one restful template extractor.
2. If you using restful template extractor, your must configured it in condition judgement model by define your URI using restful template directive.
3. `{variable name}` directive is equal to `(.+)`.
4. There are some predefined placeholders for this directive. Like  `queryString`, `head` and `body`.
5. `variable name` would be a unique word, it don't have any blank symbol and couldn't equal to predefined placeholder. (Because we would store the url variables by using your defined name as a key in url variable store.)

**Predefined placeholder**
1. `{queryString[variable]}` means exist query string, if you leave the variable blank like `{queryString}`, this would append all query string from client.
2. `{head[variable]}` would exactor header value.
3. `{body[variable]}` would just get the variable from request body(Ajax, url encoded, multipart).

**Best practice**
We have a public restful api for user login:

Name           | Variables
---------------- | --------------
GET              | `/api/v3/account/login`
Query String | `username={username}&password={password}&apiKey={apiKey}`
Rewrite         | `/dashboard/account?action=login&version=v3&username={username}&password={password}`

This would be defined like:
```
"conditions": [
    {
        "type": "URI",
        "operator": "restful",
        "value": "/api/{version}/{service}/{action}"
    }
]

"handle": {
    "trim_qs": false,
    "url_tmpl": "/dashborad/{service}?action={action}&version={version}&{queryString}",
    "log": true
}
```

A real request could like:
```
GET    http://orange_request_host:8888/api/v3/account/login?username=syhily&password=123456&apiKey=312b3b123123ubcbjkh324

REWRITE    http://upstream_service_host:8080/dashborad/account?action=login&version=v3&username=syhily&password=123456&apiKey=312b3b123123ubcbjkh324
```

**Comment by sumory** [comment]
As the final implementation of `extractor` for Orange, there are two extractor designed for the above specifics called `index extractor` and `template extractor`.

#### index extractor

This is the default extractor for Orange v0.1.*. And now one small change is added to it which works well with backward compatibility. The new feature is named as `default value`.

index extractor configuration format:
```
"extractor": {
        "type": 1, // index extractor
        "extractions": [
            {
                "type": "Query",
                "name": "wd"
            },
            {
                "type": "Header",
                "name": "from",
                "default": "this_is_default_value" // used as default value if `from` not exists in "Header"
            }
        ]
}
```

then use these variables extracted with this grammar `${1}` or `${2}` ...

####

**Comment by syhily** [comment]
So, the only restriction on `template extractor` is that we could only have one URI extractor.

**Comment by sumory** [comment]
one request one `uri` one `extraction` for "URI" type.

**Comment by antong530** [comment]
您好，这边想通过proxy_pass对url进行重写，但是后面的参数是不确定的，用您的queryString没有参数，请问这样该怎么解决

**Comment by sumory** [comment]
proxy_pass的uri是可以通过配置自定义的，而且默认情况下“分流”插件不会覆盖或者抹除原来的请求参数。
如果有更细粒度的url控制需求请使用“URL重定向“或”URI重写“插件。
