### ISSUE TITLE
rate_limiting插件写共享内存竞态问题

### ISSUE THREAD

**Issue by zhousoft** [sumory/orange#151]
自己的项目改写了rate_limiting插件，用redis来实现集群全局限流。此外增加了降级机制，在redis挂掉的时候放弃用redis统计，使用插件原有的写共享内存的方式实现单机限流。
但是查看rate_limiting的代码实现，在对共享内存中的计数进行incr操作时，先读取计数值，计数值不存在置0，存在的话执行incr操作，虽然require了resty.lock模块，但是并没有使用lock来解决原子性问题，这样做在高并发的情况下是不是会存在竞态问题，是基于什么考虑没有使用lock呢？因为我看见counter.lua模块的get_or_set方法中实际上是使用了lock的，但是该方法整个限流插件中并没有调用。

**Comment by sumory** [comment]
shared dict的`incr`本身是并发安全的，counter包装的incr方法在第一步get发现没有然后初始化的时候不是安全的，但考虑到最多也只会浪费掉worker个数的计数，为了性能就没有使用lock。
当然你的场景非常严格的话也可以加上lock。:)

**Comment by zhousoft** [comment]
感谢回答，看来这里确实是只能在性能和场景需求之间做取舍了:)
