### ISSUE TITLE
EXPIRE_TIME 取值看不懂

### ISSUE THREAD

**Issue by ncubrian** [sumory/orange#154]
orange/plugins/rate_limiting/counter.lua 文件中的
```
local EXPIRE_TIME = {
    Second = 60, -- 59s+
    Minute = 180, -- 120s+
    Hour = 3720, -- 120s+
    Day = 86520 -- 120s+
}
```
想问一下为什么都增加了后面注释的秒数，谢谢！

**Comment by sumory** [comment]
即增加120s的buffer，防止一些边界情况。比如Hour一般是3600秒，但加上一个120就是3720.

**Comment by ncubrian** [comment]
那对于Second，边界情况是指0.5秒的时候开始，1s的时候缓存就会到期吗？那如果exptime设为60，不是要60s后才到期，但是实际测试下来限流基本上是符合预期的，是1s后到期，这个有点不理解。

**Comment by sumory** [comment]
这个buffer只用于这部分数据在内存中多驻留多久，并不会用于“限流”判断，所以只要避过了“临界点”，想定多少都行，我认为120秒足够了，所以就定了120。当然你也可以定1、10、100、1000等等等。

**Comment by ncubrian** [comment]
原来关键点在这里，这个limit_key是会随时间变化的，非常感谢！
```
    local current_timetable = utils.current_timetable()
    local time_key = current_timetable[limit_type]
    local limit_key = rule.id .. "#" .. time_key
```
