### ISSUE TITLE
未发布的规则提示

### ISSUE THREAD

**Issue by zhousoft** [sumory/orange#159]
后台界面中如果能够增加如下的功能应该会大大提升后台的易用性:)
修改了规则后，在页面上某处展示未同步的规则数，并标示出来，避免了不熟悉的人使用时配置完规则忘记同步导致nginx中运行规则与后台页面展示的规则不一致。

**Comment by sumory** [comment]
"同步"指的是重新从数据库加载配置，主要用于在节点A修改配置后，在节点B通过点击”同步“来更新自己节点内的配置。
对于节点A来说，只要通过界面修改了配置就是已经应用到这个节点了，并不需要点击“同步”按钮才生效。

**Comment by zhousoft** [comment]
thanks，确实是我疏忽了。
其实是这样的，后台我是自己重构了，单独部署了一套web应用。目的是想将dashboard和网关剥离开，用一套后台来管理所有的集群，配置修改还是通过数据库，修改完成后通过配置中心同步到所有选择节点上，因此会出现我说的问题，我这里是计划加上这部分方便做规则的撤销和回滚操作。
因为重构的时间有点早，有点忘记orange原来的同步语义跟我改动之后的已经不一样了：）
