### ISSUE TITLE
如何不同端口访问

### ISSUE THREAD

**Issue by techzhou** [sumory/orange#164]
##### 需求或场景

两个站点分别是 abc.com:1000 abc.com:2000, 分别对应内部 10.0.0.1:3000 10.0.0.2:4000

1000和2000的端口通过防火墙双向转换到orange的80上

##### 使用的插件

divide

##### 具体的配置

匹配host

##### 期望的结果

配置分流到不同的站点上

##### 错误的结果

无法成功分别，host应该不是http_host的缘故

**Comment by sumory** [comment]
不建议在使用域名了，还要再加一个端口，可以直接使用子域名

**Comment by techzhou** [comment]
我也不想啊 历史遗留问题 只是想问问有啥好的解决办法没

**Comment by sumory** [comment]
简单来的话，可以这样，在进入orange之前先在abc.com:1000和abc.com:2000对应的nginx配置中设置一个header，比如叫"from_server"， 然后orange里根据这个header值来分流就好了。
诸如此类的技巧，总结下来就是在进入orange前设置一个orange能识别的标识。

**Comment by noname007** [comment]
@sumory 获取把port 也可以提取出来，放到条件表达式里，就解决了。哈哈。
