### ISSUE TITLE
如何安装依赖包

### ISSUE THREAD

**Issue by imocat** [sumory/orange#168]
关于第三方依赖包，是使用 luarocks 还是 opm ？还是将依赖安装到 orange lib 目录

**Comment by sumory** [comment]
orange短期内不打算引入包管理器，现在已发布的版本也不需要额外安装第三方包

**Comment by imocat** [comment]
0.7.0-dev 版本中，有 lua-resty-dns-client 依赖，这个会调整吗？

**Comment by sumory** [comment]
orange短期内不打算引入包管理器
