### ISSUE TITLE
init_by_lua error: init_by_lua:2: module 'orange.orange' not found

### ISSUE THREAD

**Issue by libao2235** [sumory/orange#170]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景

api server

##### 期望的结果
这个报错有时候有，有时候没有正常。

##### 错误的结果

2017/12/26 16:12:49 [error] 3143#0: init_by_lua error: init_by_lua:2: module 'orange.orange' not found:
	no field package.preload['orange.orange']
	no file '../orange/orange.lua'
	no file '/usr/local/lor/orange/orange.lua'
	no file '/usr/local/openresty/site/lualib/orange/orange.ljbc'
	no file '/usr/local/openresty/site/lualib/orange/orange/init.ljbc'
	no file '/usr/local/openresty/lualib/orange/orange.ljbc'
	no file '/usr/local/openresty/lualib/orange/orange/init.ljbc'
	no file '/usr/local/openresty/site/lualib/orange/orange.lua'
	no file '/usr/local/openresty/site/lualib/orange/orange/init.lua'
	no file '/usr/local/openresty/lualib/orange/orange.lua'
	no file '/usr/local/openresty/lualib/orange/orange/init.lua'
	no file './orange/orange.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/orange/orange.lua'
	no file '/usr/local/share/lua/5.1/orange/orange.lua'
	no file '/usr/local/share/lua/5.1/orange/orange/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/orange/orange.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/orange/orange/init.lua'
	no file '/usr/local/openresty/site/lualib/orange/orange.so'
	no file '/usr/local/openresty/lualib/orange/orange.so'
	no file './orange/orange.so'
	no file '/usr/local/lib/lua/5.1/orange/orange.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/orange/orange.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/site/lualib/orange.so'
	no file '/usr/local/openresty/lualib/orange.so'
	no file './orange.so'
	no file '/usr/local/lib/lua/5.1/orange.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/orange.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	init_by_lua:2: in main chunk

**Comment by sumory** [comment]
安装不对，请检查安装步骤

**Comment by libao2235** [comment]
有什么顺序吗？谢谢

**Comment by libao2235** [comment]
为什么有的时候可以正常启动呢？不明白？

**Comment by libao2235** [comment]
root@nginx-orange-1 conf]# orange start
[INFO] Orange: 0.6.4
[INFO] ngx_lua: 10011
[INFO] nginx: 1013006
[INFO] Lua: LuaJIT 2.1.0-beta3
[INFO] args:
[INFO] 	ngx_conf:/usr/local/orange/conf/nginx.conf
[INFO] 	orange_conf:/usr/local/orange/conf/orange.conf
[INFO] 	prefix:/usr/local/orange
[INFO] args end.
[INFO] Start orange command execute.
[INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf 
nginx: [error] [lua] orange.lua:73: init(): Startup error: ../orange/store/mysql_db.lua:6: module 'resty.mysql' not found:
	no field package.preload['resty.mysql']
	no file '../resty/mysql.lua'
	no file '/usr/local/lor/resty/mysql.lua'
	no file '/usr/local/lor/bin/resty/mysql.lua'
	no file '/usr/local/openresty/site/lualib/resty/mysql.so'
	no file '/usr/local/openresty/lualib/resty/mysql.so'
	no file './resty/mysql.so'
	no file '/usr/local/lib/lua/5.1/resty/mysql.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/mysql.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/site/lualib/resty.so'
	no file '/usr/local/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
[root@nginx-orange-1 conf]# vim nginx.conf
[root@nginx-orange-1 conf]# orange start
[INFO] Orange: 0.6.4
[INFO] ngx_lua: 10011
[INFO] nginx: 1013006
[INFO] Lua: LuaJIT 2.1.0-beta3
[INFO] args:
[INFO] 	ngx_conf:/usr/local/orange/conf/nginx.conf
[INFO] 	orange_conf:/usr/local/orange/conf/orange.conf
[INFO] 	prefix:/usr/local/orange
[INFO] args end.
[INFO] Start orange command execute.
[INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf

**Comment by fly2leoo** [comment]
http://blog.csdn.net/fly2leo/article/details/73687426

**Comment by libao2235** [comment]
难道是版本问题，0.6.4需要什么版本的openresty版本？

**Comment by sumory** [comment]
我一直用的是1.11.2版本，没在最新版上测过

**Comment by libao2235** [comment]
测试了一下最新版本不行，openresty-1.11.2.5.tar.gz 这个版本正常

**Comment by sumory** [comment]
ok，下个版本修复

**Comment by libao2235** [comment]
感觉是配置文件问题
user www www;
worker_processes  auto;
worker_rlimit_nofile 51200;

events {
    use epoll;
    worker_connections  4096;
    multi_accept on;
}

# optional: path of orange.conf
env ORANGE_CONF;

http {
    #resolver 114.114.114.114; # replace it with your favorite config
    charset UTF-8;
    include ./mime.types;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" "$upstream_addr"'
                      '"$upstream_response_time" "$request_time"';

    access_log  ./logs/access.log  main;
    error_log ./logs/error.log info;

    default_type application/octet-stream;
    server_names_hash_bucket_size 128;
    client_header_buffer_size 32k;
    large_client_header_buffers 4 32k;
    client_max_body_size 1024m;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 120;
    server_tokens off;
    tcp_nodelay on;

    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 128k;

    #Gzip Compression
    gzip on;
    gzip_buffers 16 8k;
    gzip_comp_level 6;
    gzip_http_version 1.1;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;
    gzip_types
        text/xml application/xml application/atom+xml application/rss+xml application/xhtml+xml image/svg+xml
        text/javascript application/javascript application/x-javascript
        text/x-json application/json application/x-web-app-manifest+json
        text/css text/plain text/x-component
        font/opentype application/x-font-ttf application/vnd.ms-fontobject
        image/x-icon;
    gzip_disable "MSIE [1-6]\.(?!.*SV1)";

    #If you have a lot of static files to serve through Nginx then caching of the files' metadata (not the actual files' contents) can save some latency.
    open_file_cache max=1000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    geo $whiteiplist {
        default 1;
        10.120.0.0/16 0;
        }
    map $whiteiplist $limit{
        1 $binary_remote_addr;
        0 "";
        }

    limit_conn_zone $limit zone=conn:10m;
    limit_req_zone $limit zone=reqps:10m rate=100r/s;


    #upstream default_upstream {
    #    server localhost:8001;
    #}


    #----------------------------Orange configuration-----------------------------
    lua_package_path '../?.lua;/usr/local/lor/?.lua;;';
    lua_code_cache on;

    lua_shared_dict orange_data 20m; # should not removed. used for orange data, e.g. plugins configurations..

    lua_shared_dict status 1m; # used for global statistic, see plugin: stat
    lua_shared_dict waf_status 1m; # used for waf statistic, see plugin: waf
    lua_shared_dict monitor 10m; # used for url monitor statistic, see plugin: monitor
    lua_shared_dict rate_limit 10m; # used for rate limiting count, see plugin: rate_limiting
    lua_shared_dict property_rate_limiting 10m; # used for rate limiting count, see plugin: rate_limiting



    init_by_lua_block {
        local orange = require("orange.orange")
        local env_orange_conf = os.getenv("ORANGE_CONF")
        print(string.char(27) .. "[34m" .. "[INFO]" .. string.char(27).. "[0m", [[the env[ORANGE_CONF] is ]], env_orange_conf)

        local config_file = env_orange_conf or ngx.config.prefix().. "/conf/orange.conf"
        local config, store = orange.init({
            config = config_file
        })

        -- the orange context
        context = {
            orange = orange,
            store = store,
            config = config
        }
    }

    init_worker_by_lua_block {
        local orange = context.orange
        orange.init_worker()
    }

    # main server
    server {
        listen       80;
        #server_name  my_domain.com;

        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }

        location / {
            set $upstream_host $host;
            set $upstream_url 'http://default_upstream';

            rewrite_by_lua_block {
                local orange = context.orange
                orange.redirect()
                orange.rewrite()
            }

            access_by_lua_block {
                local orange = context.orange
                orange.access()
            }

            # proxy
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Scheme $scheme;
            proxy_set_header Host $upstream_host;
            proxy_pass $upstream_url;


            header_filter_by_lua_block {
                local orange = context.orange
                orange.header_filter()
            }

            body_filter_by_lua_block {
                local orange = context.orange
                orange.body_filter()
            }

            log_by_lua_block {
                local orange = context.orange
                orange.log()
            }
        }

        location /robots.txt {
            return 200 'User-agent: *\nDisallow: /';
        }
    }

    # default upstream server
    server {
        listen 8001;
        server_name localhost 127.0.0.1;
        access_log ./logs/default_upstream_access.log main;
        error_log ./logs/default_upstream_error.log;

        location / {
            content_by_lua_block {
                ngx.status = 404
                ngx.say([[404! upstream not found. Host: ]] .. ngx.var.host .. "  URI: " .. ngx.var.uri)
            }
        }
    }


    # orange dashboard server
    server {
        listen       9999;
        stub_status on;
        #server_name  localhost;
        access_log ./logs/dashboard_access.log main;
        error_log ./logs/dashboard_error.log info;

        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }

        location /robots.txt {
            return 200 'User-agent: *\nDisallow: /';
        }

        # dashboard的静态文件
        location ~* /static/(.*) {
            alias ./dashboard/static/$1;
        }

        location / {
            set $template_root '';
            content_by_lua_block {
                context.views_path = ngx.config.prefix() .. "/dashboard/views"
                local main = require("dashboard.main")
                main:run()
            }
        }
    }

    # api server
    #server {
    #    listen       7777;
    #    #server_name  localhost;
    #    access_log ./logs/api_access.log main;
    #    error_log ./logs/api_error.log info;
    
    #    location = /favicon.ico {
    #        log_not_found off;
    #        access_log off;
    #    }

    #   location /robots.txt {
    #       return 200 'User-agent: *\nDisallow: /';
    #    }

    #   location / {
    #        content_by_lua_block {
    #            local main = require("api.main")
    #            main:run()
    #        }
    #    }
    #}

########################## vhost #############################
    include vhost/*.conf;
}

**Comment by sumory** [comment]
如果你修改了nginx.conf，那么`lua_package_path`需要配成合理的orange所在路径，让OpenResty能识别到

**Comment by libao2235** [comment]
ua_package_path '../?.lua;/usr/local/lor/?.lua;/usr/local/orange/?.lua;';
nginx: [error] [lua] orange.lua:73: init(): Startup error: ../orange/store/mysql_db.lua:6: module 'resty.mysql' not found:
	no field package.preload['resty.mysql']
	no file '../resty/mysql.lua'
	no file '/usr/local/lor/resty/mysql.lua'
	no file '/usr/local/orange/resty/mysql.lua'
	no file '/usr/local/openresty/site/lualib/resty/mysql.so'
	no file '/usr/local/openresty/lualib/resty/mysql.so'
	no file './resty/mysql.so'
	no file '/usr/local/lib/lua/5.1/resty/mysql.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/mysql.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/site/lualib/resty.so'
	no file '/usr/local/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by libao2235** [comment]
我知道，谢谢您的回答，应该不是BUG，是配置文件问题
但是我不知道为什么有的时候正常，断开xshell就不能正常启动了。
但是这么写就正常了
lua_package_path '../?.lua;/usr/local/lor/?.lua;;/usr/local/orange/?.lua;;';

**Comment by sumory** [comment]
应该是不同环境识别到“默认的”的lua_package_path不一样导致的，最好还是在配置文件里显式指定你想要的路径就好。
