### ISSUE TITLE
全局统计里conn有记录，没有请求记录

### ISSUE THREAD

**Issue by libao2235** [sumory/orange#173]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景

api

##### 使用的插件

stat

##### 具体的配置

resty 0.20
nginx version: openresty/1.13.6.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../iconv-nginx-module-0.14 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.07 --add-module=../ngx_postgres-1.0 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.11 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.18 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.08 --add-module=../ngx_stream_lua-0.0.3 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-http_stub_status_module --with-stream --with-stream_ssl_module --with-http_ssl_module

##### 期望的结果

已经安装openresty的--with-http_stub_status_module这个模块。是访问量小就不显示吗？

##### 错误的结果

描述实际的结果， 比如错误的输出或截图

![image](https://user-images.githubusercontent.com/12504429/34553605-5462f1fa-f163-11e7-89e3-6225817a2184.png)

  需要配置什么吗？谢谢

**Comment by sumory** [comment]
你随便找个压测工具，比如ab，多发一些请求看看

**Comment by libao2235** [comment]
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        3   42 122.6     10    3011
Processing:    69  330 112.7    310    1020
Waiting:       65  216  82.8    230     871
Total:         80  372 164.7    340    3330
还是没有数据
![image](https://user-images.githubusercontent.com/12504429/34591546-57921a4a-f1f9-11e7-9b68-10fd8e3b6573.png)

这个是openresty配置
[root@nginx-orange-1 logs]# resty -v
resty 0.20
nginx version: openresty/1.13.6.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../iconv-nginx-module-0.14 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.07 --add-module=../ngx_postgres-1.0 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.11 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.18 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.08 --add-module=../ngx_stream_lua-0.0.3 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-http_stub_status_module --with-stream --with-stream_ssl_module --with-http_ssl_module

**Comment by libao2235** [comment]
感觉像是那里没配置正常，但是配置status页还有数据
![image](https://user-images.githubusercontent.com/12504429/34591745-aa8391a6-f1fa-11e7-9f85-ff0e28efa899.png)

**Comment by libao2235** [comment]
这个请求是怎么得到的？感觉那里配置错了。

**Comment by sumory** [comment]
没遇到过你这个问题，也没有收到过类似反馈，暂时没怀疑点。
你可以安装后，然不要自己再做什么额外的配置试试；或者在orange/orange/plugins/monitor/handler.lua里打几个日志看看。

**Comment by libao2235** [comment]
这是 dashboard_error.log这个的日志

2018/01/05 13:50:21 [info] 9749#0: *7 [lua] dashboard.lua:32: load_plugin_api(): load route, uri:/waf/fetch_config, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] dashboard.lua:32: load_plugin_api(): load route, uri:/waf/selectors/:id/rules/order, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] dashboard.lua:32: load_plugin_api(): load route, uri:/waf/sync, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] dashboard.lua:32: load_plugin_api(): load route, uri:/waf/selectors/order, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] dashboard.lua:32: load_plugin_api(): load route, uri:/waf/selectors, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] dashboard.lua:32: load_plugin_api(): load route, uri:/waf/enable, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] dashboard.lua:32: load_plugin_api(): load route, uri:/waf/selectors/:id/rules, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] dashboard.lua:32: load_plugin_api(): load route, uri:/waf/stat, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [error] 9749#0: *7 [lua] dashboard.lua:11: load_plugin_api(): [plugin's api load], plugin_api_path:orange.plugins.divide.api, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] base_api.lua:64: build_method(): attach method delete to BaseAPI, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] base_api.lua:64: build_method(): attach method patch to BaseAPI, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] base_api.lua:64: build_method(): attach method post to BaseAPI, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] base_api.lua:64: build_method(): attach method put to BaseAPI, client: 192.168.100.144, server: , request: "GET / HTTP/1.1", host: "192.168.100.211:9999"
2018/01/05 13:50:21 [info] 9749#0: *7 [lua] base_api.lua:64: build_method(): attach m

**Comment by libao2235** [comment]
配置文件问题。
