### ISSUE TITLE
官方文档能否增加WAF相关的白名单简单例程？

### ISSUE THREAD

**Issue by kongdj** [sumory/orange#179]
希望实现白名单，允许指定的IP或者IP段进行访问 

在nginx里使用allow 和deny 加载到对应的配置文件上就可以解决，在orange不知如何使用！
官方文档 上面很多很多都是说 参照重定向设置规则，字段有所差异。
其实nginx本来就是很多细小差异化的东西。
希望能增加简单的通用场景教程，谢谢！

**Comment by nblib** [comment]
https://github.com/nblib/notebook/blob/master/lua_nginx%E7%B3%BB%E5%88%97%E6%95%99%E7%A8%8B/%5B17%5Dorange%E6%8F%92%E4%BB%B6%E4%B9%8B%E9%98%B2%E7%81%AB%E5%A2%99.md
