### ISSUE TITLE
About proxy, AB Testing and divide

### ISSUE THREAD

**Issue by tonychee7000** [sumory/orange#18]
I had found your introduce [here](https://segmentfault.com/a/1190000004680996)

It was said orange had 6 plugins including proxy, ABTesting and divide

But your [document](http://orange.sumory.com/docs/examples/divide.html) have no more details about that

And it have no guide for newbie

**Comment by sumory** [comment]
the [document](http://orange.sumory.com/docs/) only shows some normal use cases. before using Orange, make sure you have already understood some `concept`([judge](http://orange.sumory.com/docs/judge.html)、[extractor](http://orange.sumory.com/docs/extractor.html)、[condition](http://orange.sumory.com/docs/condition.html)...) about it. And then, try more about the functions on its `Dashboard`.

**Comment by sumory** [comment]
[the official documents](http://orange.sumory.com/docs) have been updated for Orange v0.3.0. Please check the change log and the more specific description for its plugins. 😃
