### ISSUE TITLE
orange启动之后dashboard访问不到页面

### ISSUE THREAD

**Issue by 15211002483** [sumory/orange#184]
orange安装成功之后，以下是配置环境。
[root@bogon orange]# nginx -v
nginx version: openresty/1.11.2.5
[root@bogon orange]# resty -v
resty 0.19
nginx version: openresty/1.11.2.5
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled

然后访问页面是，返回的是页面名，本人初学，请教一下，多谢！
![image](https://user-images.githubusercontent.com/31949742/35765753-7523fe02-0905-11e8-87e8-86fea66ac6d1.png)

**Comment by sumory** [comment]
一般这种情况可以从以下几方面检查下：
- nginx的配置文件是否需要加`user`配置
- 本地文件是否有权限问题
- 如果修改过默认的配置请仔细检查是否有错误
