### ISSUE TITLE
upstream支持keepalive

### ISSUE THREAD

**Issue by saga1015** [sumory/orange#19]
大拿，你好，orange做API网关时，新增API时，upstream能否增加keepalive参数啊

**Comment by sumory** [comment]
Orange暂时不支持动态upstream，要先在nginx.conf里配置好upstream才能在Orange中使用(如分流插件、URL重定向插件等）。

如果要在upstream中支持keepalive，建议你在nginx.conf自行配置以下选项：
```
#proxy pass时配置HTTP协议版本
proxy_http_version 1.1;
proxy_set_header Connection "";

#upstream指令块里配置keepalive，如
keepalive 1024;
```

**Comment by saga1015** [comment]
收到，这样用也方便。哈哈
