### ISSUE TITLE
重写url包404

### ISSUE THREAD

**Issue by greedKNO** [sumory/orange#197]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

自己重写一个请求 http://10.0.1.50:8888/rewrite?a=abc
期望的url是：http://10.0.1.50:8888/to_rewrite?search=abc
![image](https://user-images.githubusercontent.com/28565007/36882836-34d63e0c-1e11-11e8-9b9b-df9020ac01a3.png)

但是结果却是
![image](https://user-images.githubusercontent.com/28565007/36882899-79406914-1e11-11e8-9e14-8916c8bc85f5.png)
请问该怎么做？

**Comment by sumory** [comment]
你没有任何去实现这个URI，当然是404了。。。

**Comment by greedKNO** [comment]
![image](https://user-images.githubusercontent.com/28565007/37015641-5bbd2118-2143-11e8-8829-74b09f4bb0bf.png)
我在里面又写了一个重定向，单独的重定向是可以的，但是通过重写然后转到重定向却不行
