### ISSUE TITLE
能否支持复杂一点的拦截规则

### ISSUE THREAD

**Issue by cmdares** [sumory/orange#198]
例如：
1、能否拦截同一个客户端的IP地址访问的某一URL服务，连续N秒访问频次达到M次之上的那些IP地址会被记录在系统上，同时禁用这些IP地址X个小时。在不重启的情况下激活规则。同时也支持手工解除某系IP的锁定。
谢谢。

**Comment by sumory** [comment]
- 官方插件只会尽量提供`可通用`的`尽量小粒度`的功能，这样才能通过`排列组合`被尽可能多的场景**复用**
- 过于个性化(不够通用)、复杂或与业务紧密相连的功能请自行开发插件
