### ISSUE TITLE
orange是否参考了VeryNginx的设计？如果有的话请注明

### ISSUE THREAD

**Issue by alexazhou** [sumory/orange#2]
很不错的作品

不知在设计orange的时候是否参考了VeryNginx的设计。如果有的话，出于对作者的尊重，请在Readme中注明这一点，谢谢

**Comment by sumory** [comment]
@alexazhou 
- Orange开始于去年1月份，写的过程中诞生了[lor](https://github.com/sumory)
- lor稳定后差不多是2月底，然后github上那个时候VeryNginx已经很多关注了吧？具体记不得了。我看过好几个Gateway(包括WAF)的代码，包括Kong、新浪的ABTesting、FreeWAF，Adobe的一个、还有几个不是很完善的开源代码。VeryNginx是其中一个，但除了Kong之外功能上和架构上都不能满足我的需要。
- 我们内部的业务需求就是简单的WAF、转发、重定向和分流、ABTesting，这些业务形态应该算是一个Gateway的基础功能了。比如我个人觉得功能最全面的Kong就是一个比较好的实现。
- 如果要说哪里借鉴了VeryNginx，orange的“监控”部分目前开放出来的功能是跟VeryNginx类似的，还有如果你看过orange的代码的话，Matcher和Action这个**概念**我是参考VeryNginx的，比如关于Matcher的的判断有一个test_var函数是使用VeryNginx的，但这些概念我已经做了扩展或者改变，比如多条件逻辑支持、复杂的逻辑条件表达式支持等等。
- Orange的架构设计多半是参考的Kong，尤其是插件机制，但功能上是根据我自己这边的业务需要而设计的
- Orange现在还在内部稳定开发中，一些遗留的代码或者概念后期都可能做更改，至少在v0.1.0版本之前架构和代码都是易变的

最后，非常感谢你能开放出像VeryNginx这样优秀的开源软件给大家使用，在下个版本中我会把参考的其他代码或是项目的链接补上。如果你觉得我使用的地方有任何侵权的还请指出，我删掉或做下重构，:smile:

**Comment by alexazhou** [comment]
* 从Github上面的代码提交纪录来看，Orange第一次提交是在2016年3月19日，而且从提交纪录来看是逐步完成的，如果是从去年开始开发的，为什么Github纪录是这样的呢？而VeryNginx在2016年1月底完成，到16年2月获得1000＋ Star，在Orange第一次提交到Github之前，VeryNginx已经是社区比较知名的作品了

* 对一个Gateway来说，WAF确实是一个基本的功能。而Redirect，Rewrite并不算是Gatway基本的功能吧？VeryNginx是想把Nginx的配置层完全在前端实现，才会实现这些功能。
>* 比如说你参考的Kong，他的Readme中整篇并找不到Redirect或Rewrite这样的描述...更何况的是和VeryNginx设计的如此相似的Redirect，Rewrite功能，连配置参数都一样
> * 新浪的ABTesting也没有这些功能

* 监控部分确实很相似

* Matcher & Action 这个设计，是VeryNginx的一个基本框架，主要是提供了一种简洁可行的方法来筛选要处理的请求，这是VeryNginx给开源社区的贡献。Orange这部分的结构和VeryNginx基本是一样的，只是扩展了逻辑判断，底子都是一样的（VeryNginx本身就支持多个条件，但是默认是全与运算）。
>这里非常相似，我就说一个细节，VeryNginx原创使用约等于号来表示正则匹配，等号表示字符串匹配。就连这点来说，Orange都和VeryNginx一模一样。

#### 总的来说，Orange的设计和VeryNginx真是出奇的相似，让人感觉Orange其实就是把VeryNginx用不同的方式又重新实现了一遍。。。

最后我想你可能误会我的意思了，VeryNginx开源出来，是想对大家有所帮助，就算你照抄个一摸一样的也是没有问题的，这是你的自由。只是说这个作品是自己设计的，这样就不合适了。

以Orange和VeryNginx的相似程度，我建议你在Readme中加上一个说明，这样会比较合适，我想你应该可以处理好这个

**Comment by alexazhou** [comment]
还有，这么快就关闭了Issue，恐怕不合适吧

**Comment by sumory** [comment]
其实我也是挺醉的。。。其他的我也不多说了吧。关闭issue的理由只是我觉得这不是一个软件使用问题。此外，我也说了一些大路上的概念还有类似于test_var的代码是拿的VeryNginx的。真没想到会碰到这种事儿。。

**Comment by alexazhou** [comment]
我不太明白我那儿做的不对，让你醉了？如果有还请指出来

另外你是否打算加上说明呢？

**Comment by sumory** [comment]
@alexazhou 

 - 如果orange让你感到有侵权的地方，我深感抱歉。  
 - 我也没有公开发表orange是完全我自己设计的言论。
 - 正如issue里我首次回复你的，我也承认orange的一些工具代码是参考了VeryNginx类似的设计，但像Matcher、Action之类的概念真的是各种语言、框架、库都有的东西，我并不觉得我有侵犯了你什么独有设计的问题，如果你认为这是你的核心设计，我保留对此条的看法。
 - 你的开源协议是LGPL，这个协议的条款相信可能你比我更清楚，据此在引用了你的代码里我没有注明出处，我本以为按照条款是合适的，但没想到会对你造成困扰，对这一点我会修正orange的代码。  
 - 第一次回你的issue就说明了我参考了很多已有的前辈的框架或是类似项目，尤其是Kong，而在我的代码和文档网站里也注明了Kong，所以我并没有恶意的剽窃或是引用别人的东西并把它据为己有的想法和做法。
 - 为了不给你和大家造成困扰，下个版本我会把所有你认为与VeryNginx相似的地方全都去除或是重构。也欢迎你继续监督。

对你造成的困扰，再次深表歉意。

**Comment by alexazhou** [comment]
如果orange让你感到有侵权的地方，我深感抱歉
>这个没有关系，有一些意见不一样是很正常的事情，大家有问题互相协商解决就好，并没有什么大不了的，都是就事说事。

我也没有公开发表orange是完全我自己设计的言论
>你的确没有直接说这一点，但也并没有在任何地方说明本项目有 ｀模仿｀或者｀参考｀或者其他项目的信息，这其实就是一种暗示。如果你在Github上面发表了一个开源项目，但是不注明其实是 **模仿** 了另外一个项目，那我们绝大多数人就会默认这是你原创的

正如issue里我首次回复你的，我也承认orange的一些工具代码是参考了VeryNginx类似的设计，但像Matcher、Action之类的概念真的是各种语言、框架、库都有的东西，我并不觉得我有侵犯了你什么独有设计的问题，如果你认为这是你的核心设计，我保留对此条的看法。
>设计是一门学问，技术含量，难度，和所花费的心力都不亚于编程，事实上如果有了成熟的设计，需求不会变根，实现一遍是最简单不过了。Matcher 和 Action  的叫法确实很多地方都有，我选了这个名字，也是希望大家一看就知道是什么。但我要说的是，在 VeryNginx 之前，并没有任何一个 waf 或者其他的什么玩意儿把这套东西设计成这样子，这足以说明设计的独创性。事实上你如果水平够的话，完全可以不用这套，设计出来一个不一样的 (我说的是基础概念的不一样，在 Matcher 上面稍微扩展一下，很难算是不一样)。

你的开源协议是LGPL，这个协议的条款相信可能你比我更清楚，据此在引用了你的代码里我没有注明出处，我本以为按照条款是合适的，但没想到会对你造成困扰，对这一点我会修正orange的代码。
>VeryNginx 的开源协议确实是LGPL，选这个协议是为了让大家用起来比较自由，并不是用了几行就要引用我，或者也要开源。

>所以我的代码你可以用，完全没问题，我在前面的回答中也已经指出来了这点。

>现在的重点是 Orange 和 VeryNginx 如此相似，我觉得在这种情况下你标注出来 **模仿** 了VeryNginx会比较合适，然后我也是向你提出这个建议，并不是强制你怎么做。这里具体怎么做其实是你的自由。只是当你做的事情不合适的时候，我也有权力把情况公开，让更多的人看到，大家将会有自己的判断。

第一次回你的issue就说明了我参考了很多已有的前辈的框架或是类似项目，尤其是Kong，而在我的代码和文档网站里也注明了Kong，所以我并没有恶意的剽窃或是引用别人的东西并把它据为己有的想法和做法
>关于你提到的 Orange 是参考了 Kong ，我有三点要说明的
>* Orange 是否参考了 Kong 和是否模仿了 VeryNginx 没有任何关系，也没办法互相证明
* 我觉得 Orange目前的版本来说， **模仿** VeryNginx 的程度比模仿 Kong 的程度超过太多，如果你对这点有异议，我建议去找一些第三方人士进行公平的鉴定
* 就算是对于Kong来说，我并没有在 Readme 中看到有模仿Kong，在文档网站中，我略看了一下也没有能注意到

为了不给你和大家造成困扰，下个版本我会把所有你认为与VeryNginx相似的地方全都去除或是重构。也欢迎你继续监督
>我不太知道我提出的建议是哪里侵犯了你的权益，让你坚持不愿意加上参考了 VeryNginx 的说明，我本来以为这是个很简单的事情，如果方便的话请告知我，方便我以后改进，当然告知与否绝对是你的自由。Anyway，既然你已经决定了处理方式，那我尊重你的决定。

最后，我想在你把和 VeryNginx 相似的地方完全移除之前，还是加上引用说明比较好。

**Comment by sumory** [comment]
哥们，我真的呵呵了！你开心就好

**Comment by alexazhou** [comment]
我感觉你虽然说很抱歉，但是实际上并没有诚意。

实际上 [Macdown](https://github.com/MacDownApp/macdown) 的作者这样的，我就很欣赏，怎么做是你的自由，但请敢做敢当。
