### ISSUE TITLE
求助，为什么安装好之后没有样式

### ISSUE THREAD

**Issue by AngeliaCheng** [sumory/orange#20]
我按照安装说明进行操作，orange的服务也启动起来了，但是却没有样式，请指教可能是哪里出了问题，谢谢

**Comment by sumory** [comment]
没有样式？你说的是dashboard？你有更改过配置文件吗？是不是mime.types没配上？可以使用chrome或者firefox查看下静态文件的加载情况

**Comment by AngeliaCheng** [comment]
嗯，所有的css和js都是403，我是把orange装在虚拟机中，然后在本机进行访问的

**Comment by AngeliaCheng** [comment]
只改过orange.conf，改了mysql部分的内容，其他的没有改

**Comment by sumory** [comment]
检查下你的静态目录（存放css和js的目录）是否有访问权限

**Comment by AngeliaCheng** [comment]
有-drwxr-xr-x 权限

**Comment by sumory** [comment]
我没有限制静态资源的访问，也没加什么策略。看来应该是你本地配置的问题，只能你自己仔细查查看哪个环节出问题了。

**Comment by AngeliaCheng** [comment]
好的，谢谢啦

**Comment by AngeliaCheng** [comment]
找到解决方法了，在nginx.conf配置文件头部加user root：

但是真的很奇怪，我装的时候都是用root用户的，而且文件和目录权限也是正常的，不加这句话就无法加载样式文件

参考文章：
http://blog.csdn.net/ngcsnow/article/details/39394991
