### ISSUE TITLE
0.7dev左侧菜单persist打开403

### ISSUE THREAD

**Issue by we7team** [sumory/orange#200]
rt

**Comment by sumory** [comment]
@imocat

**Comment by imocat** [comment]
@we7team   please provide screenshot

**Comment by we7team** [comment]
![image](https://user-images.githubusercontent.com/4837122/37389789-9bc1918c-27a0-11e8-974a-9e394e98ae74.png)

**Comment by we7team** [comment]
![image](https://user-images.githubusercontent.com/4837122/37389883-f4d6fa32-27a0-11e8-9dfe-0c276b54045c.png)

**Comment by imocat** [comment]
提供下版本，
目前这个功能是合并到 v0.7.0-dev 分支中，我刚才测试了一下，是正常查看的。
另外纠正一下，是 404 错误，不是 403.

**Comment by we7team** [comment]
我之前是clone的v0.7.0-dev分支

**Comment by imocat** [comment]
pull 下最新版本试试
