### ISSUE TITLE
orange代理、分流问题

### ISSUE THREAD

**Issue by mqmjingba** [sumory/orange#201]
使用orange做网关时需要代理后端的应用服务，已经配置了，
nginx 配置  upstream xinfadi_upstream {
        server x.x.x.x:5050;
        server x.x.x.x:5051;
    }
正常后端接口访问路径为http://x.x.x.x:5050/microweb-home-web/homepage/index/getCardInfoList.json 当前接口可以正常访问
 控制台配置URL---Match ---/homeweb/ 
upstream url 配置地址 http://xinfadi_upstream/microweb-home-web/
通过代理后访问接口时提示404！，能否帮忙看下我的用法是否有问题？

**Comment by sumory** [comment]
以下issue供参考，看过之后，建议自己多尝试:
https://github.com/sumory/orange/issues/134
https://github.com/sumory/orange/issues/128

**Comment by mqmjingba** [comment]
@sumory  您好，我目前的配置是参照您的流程来的，而且我上面的配置如果我直接在orange的nginx配置文件里面配置是没有问题的，我现在用的版本是master，昨天已经经过了多次尝试，能否帮忙看下我上面的操作流程是否正确

**Comment by sumory** [comment]
你没试过换个upstream url试试？比如不带`/`后缀的。我建议你先通读一下那两个issue
