### ISSUE TITLE
api监听7777端口认证问题

### ISSUE THREAD

**Issue by happut** [sumory/orange#203]
##### 需求或场景

远程删除相应选择器

##### 使用的插件

HTTP Signature Auth

##### 具体的配置

暂无

##### 期望的结果

模拟9999端口的请求，可以新增、修改、但是无法删除，看到官方文档后发现是有专用的7777的端口服务来进行api调用，所以想用7777服务

##### 错误的结果

开启了认证，知道用户密码，但是不太清楚如何传递，尝试用9999登陆后生成的cookie，但是还是401，无法通过认证

**Comment by happut** [comment]
看了下源码，知道了。。。
base64(username:password)

**Comment by happut** [comment]
建议官方文档里面增加下~~~

^_^，翻遍了官网文档也没找到对应配置

**Comment by sumory** [comment]
这不是HTTP Basic Auth的基本用法吗？
