### ISSUE TITLE
作者您好，我正在使用orange进行二次，开发，我书lua的新手，请教下，orange应该怎么进行调试呢？ 能否留下一个联系方式

### ISSUE THREAD

**Issue by yu199195** [sumory/orange#204]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景

描述你想实现的功能

##### 使用的插件

针对这个需求你使用了哪个或哪几个插件

##### 具体的配置

在插件里做了什么配置， 可以截图， 一定要描述清楚你的配置

##### 期望的结果

按你选用的插件和所做的配置， 你期望的结果是什么？ 比如访问了哪个URL， 参数都是什么， 期望的输出是什么

##### 错误的结果

描述实际的结果， 比如错误的输出或截图

**Comment by sumory** [comment]
有问题请提issue，目前基于OpenResty的应用没有好太好的调试方法，打日志即可。
另外，请注意提issue的基本礼仪，你的issue正文复制了一遍模板，一个有意义的字都没有，以后这样的issue我直接关掉不予回复。
