### ISSUE TITLE
咨询分流功能 Upstream 的 FailOver 功能

### ISSUE THREAD

**Issue by alswl** [sumory/orange#205]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景

对 Upstream 中的节点进行 FailOver 配置。

##### 使用的插件

Divide 代理分流

##### 具体的配置

SKIP

##### 期望的结果

期望能够在 Divide 模式下面，提供 weight / max_fails / fail_timeout / backend  功能。

##### 错误的结果

没有找到相关配置。

**Comment by sumory** [comment]
暂不支持，目前依赖于nginx.conf里的静态配置
