### ISSUE TITLE
dashboard无法开启插件

### ISSUE THREAD

**Issue by zhushaojun65** [sumory/orange#207]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景

环境搭建, 并正确在orange-dashboard 中开启插件

##### 使用的插件

mysql:5.7, orange, orange-dashboard

##### 具体的配置

version: '3'

services:
    db:
        image: mysql:5.7
        container_name: orange-db
        environment:
            - MYSQL_DATABASE=orange
            - MYSQL_USER=orange
            - MYSQL_PASSWORD=12345678
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        ports:
          - "3306:3306"

    orange:
        depends_on: 
            - db
        build: ./orange
        environment:
            - ORANGE_HOST=db
            - ORANGE_PORT=3306
            - ORANGE_USER=orange
            - ORANGE_PWD=12345678
            - ORANGE_DATABASE=orange
        ports:
          - "7777:7777"
          - "8888:8888"
          - "9999:9999"
        links:
            - db
        container_name: gateway-orange

##### 期望的结果

能在dashboard中正确的开启插件

##### 错误的结果

在dashboard中无法正确的开启插件, 错误如下:
2018/04/16 02:23:01 [error] 95#95: *12 [lua] mysql_db.lua:30: query(): failed to connect: failed to connect: db could not be resolved (3: Host not found): nil nil, client: 172.21.0.1, server: , request: "POST /rate_limiting/enable HTTP/1.1", host: "localhost:9999", referrer: "http://localhost:9999/rate_limiting"
2018/04/16 02:23:01 [error] 95#95: *12 [lua] mysql_store.lua:91: update_enable(): MySQLStore:update error:nil, client: 172.21.0.1, server: , request: "POST /rate_limiting/enable HTTP/1.1", host: "localhost:9999", referrer: "http://localhost:9999/rate_limiting"

compose中明明已经link了db, 可是在dashboard中开启插件的时候, 一直失败

**Comment by sumory** [comment]
容器问题请自行排查
