### ISSUE TITLE
重定向与鉴权的执行顺序

### ISSUE THREAD

**Issue by evalsu** [sumory/orange#208]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景
描述你想实现的功能
测试对于同一个地址，既配置了重定向，也配置了鉴权，调用地址时是否会先执行鉴权，且鉴权不通过不执行重定向。

##### 使用的插件
针对这个需求你使用了哪个或哪几个插件
redirect、signature auth。

##### 具体的配置()
在插件里做了什么配置， 可以截图， 一定要描述清楚你的配置
重定向：
![image](https://user-images.githubusercontent.com/32758139/39790963-7790a0a4-536b-11e8-967f-ce6a2ef7350d.png)

![image](https://user-images.githubusercontent.com/32758139/39791089-29270024-536c-11e8-9c6f-032dc304ddb0.png)

鉴权：
![image](https://user-images.githubusercontent.com/32758139/39791123-68ed8476-536c-11e8-9155-bf7a6cc02902.png)

![1](https://user-images.githubusercontent.com/32758139/39791740-de8fdc8a-536f-11e8-8d30-fd02570cb214.png)

##### 期望的结果
按你选用的插件和所做的配置， 你期望的结果是什么？ 比如访问了哪个URL， 参数都是什么， 期望的输出是什么
期望鉴权能先执行，通过则执行重定向。

##### 错误的结果
描述实际的结果， 比如错误的输出或截图
重定向会先执行，重定向后没有鉴权。
![2](https://user-images.githubusercontent.com/32758139/39792930-b12cacd6-5375-11e8-904b-9eaa1c2b419b.png)

**Comment by yrjjf** [comment]
遇到类似问题，求教是否有处理方式?

**Comment by sumory** [comment]
#214 请理解什么是“重定向”什么是“重写”，另外参看issue#214的回复
