### ISSUE TITLE
启动之后访问9999端口显示index.html

### ISSUE THREAD

**Issue by shenshihala** [sumory/orange#211]
下载安装完成之后启动orange
访问9999端口返回
![image](https://user-images.githubusercontent.com/25096686/40817518-5acf92c8-6585-11e8-92c2-0a532b66c2b6.png)
相关配置如下
nginx.conf都是默认配置
![image](https://user-images.githubusercontent.com/25096686/40817747-9e10ac42-6586-11e8-9365-5b595fc9f725.png)
orange.conf
![image](https://user-images.githubusercontent.com/25096686/40817768-c0ac0850-6586-11e8-9323-a6b3e66cdb32.png)
![image](https://user-images.githubusercontent.com/25096686/40817782-c7a47660-6586-11e8-829a-63cbb13b6d42.png)

**Comment by sumory** [comment]
1. 检查是否需要在nginx.conf里配置用户
2. 检查是否路径改的有问题
