### ISSUE TITLE
设置了重定向和 HTTP Signature Auth，发现只走了重定向的规则，没有走Signature Auth

### ISSUE THREAD

**Issue by yrjjf** [sumory/orange#214]
针对`Orange使用`的提问， 对于简单几句话描述不清的问题， 请使用以下格式， 不符合格式或描述含糊不清的issue将不予回复。

##### 需求或场景

api访问时，进行鉴权和重定向

##### 使用的插件

HTTP Signature Auth  
URL Redirect

##### 具体的配置
URL Redirect 的配置如下：
{
  "redirect.selectors": {
    "61896908-9cfc-40a2-a392-41c19c8625cc": {
      "time": "2018-07-05 14:16:15",
      "enable": true,
      "type": 0,
      "id": "61896908-9cfc-40a2-a392-41c19c8625cc",
      "judge": [],
      "name": "skywalking",
      "handle": {
        "continue": true,
        "log": true
      },
      "rules": [
        "b1d1c0c9-cca5-4dba-822a-be8a3a45b445"
      ]
    }
  },
  "redirect.enable": true,
  "redirect.selector.61896908-9cfc-40a2-a392-41c19c8625cc.rules": [
    {
      "extractor": {
        "extractions": [],
        "type": 2
      },
      "enable": true,
      "id": "b1d1c0c9-cca5-4dba-822a-be8a3a45b445",
      "judge": {
        "type": 2,
        "conditions": [
          {
            "value": "/to_lujk",
            "operator": "match",
            "type": "URI"
          },
          {
            "value": "1",
            "name": "to_lujk",
            "operator": "=",
            "type": "Query"
          }
        ]
      },
      "name": "skywalking---压力测试环境",
      "handle": {
        "redirect_status": "301",
        "url_tmpl": "http://10.253.125.85:8080",
        "log": true,
        "trim_qs": false
      },
      "time": "2018-07-05 11:53:46"
    }
  ],
  "redirect.meta": {
    "selectors": [
      "61896908-9cfc-40a2-a392-41c19c8625cc"
    ]
  }
}

HTTP Signature Auth  配置如下：
{
  "signature_auth.meta": {
    "selectors": [
      "e433d3b4-a68c-4603-845b-2ba1fd8ba13a"
    ]
  },
  "signature_auth.selectors": {
    "e433d3b4-a68c-4603-845b-2ba1fd8ba13a": {
      "time": "2018-07-05 15:55:52",
      "enable": true,
      "type": 0,
      "id": "e433d3b4-a68c-4603-845b-2ba1fd8ba13a",
      "judge": [],
      "name": "skywalking",
      "handle": {
        "continue": true,
        "log": true
      },
      "rules": [
        "cbc4dc76-baa0-4c99-8791-521b51c843d2"
      ]
    }
  },
  "signature_auth.enable": true,
  "signature_auth.selector.e433d3b4-a68c-4603-845b-2ba1fd8ba13a.rules": [
    {
      "extractor": {
        "extractions": [
          {
            "type": "Query",
            "name": "uuid"
          },
          {
            "type": "Query",
            "name": "pjcod"
          }
        ],
        "type": 1
      },
      "enable": true,
      "id": "cbc4dc76-baa0-4c99-8791-521b51c843d2",
      "judge": {
        "type": 2,
        "conditions": [
          {
            "value": "/to_lujk",
            "operator": "match",
            "type": "URI"
          },
          {
            "value": "1",
            "name": "to_lujk",
            "operator": "=",
            "type": "Query"
          }
        ]
      },
      "name": "api",
      "handle": {
        "log": true,
        "credentials": {
          "signame": "sig",
          "secretkey": "1234"
        },
        "code": 401
      },
      "time": "2018-07-05 14:08:24"
    }
  ]
}

##### 期望的结果

访问时，在鉴权成功的情况下，能正常重定向到设置好的URL串上。

##### 错误的结果

实际的情况，不管提供的鉴权是否正常，都跳转到了重定向的URL上面。
把URL Redirect 规则删除后。重新测试。发现鉴权正常，提示not  found的错误(因为没有正常配置重定向)。访问提供的是错误密钥时，提示访问不允许。 说明鉴权功能是正常的。 

http://domain.com/xxxxx?uuid=akdflja1299330aa&pjcod=11111&sig= md5(uuid+pjcod+secret key)

**Comment by yrjjf** [comment]
通过权重值调整， 优先匹配了鉴权。 但是发现一个问题。 鉴权失败的情况下，仍旧进行了后续的其他规则匹配。但是鉴权失败的，也正常重定向了。

**Comment by sumory** [comment]
请注意rewrite阶段(重定向插件、rewrite重写插件)在access阶段(auth插件)之前，这是OpenResty的运行机制，建议先学习下OpenResty相关知识再用Orange

**Comment by yrjjf** [comment]
实际测试情况是，一旦匹配LRU重定向，就不会再去匹配鉴权。 
修改了鉴权插件的  SignatureAuthHandler.PRIORITY 值， 可以让API连接先进行鉴权。 但是鉴权失败的问题，仍旧被匹配了LRU重定向，不知道是否是没配置好，求教。
