### ISSUE TITLE
发现rewrite插件 bug

### ISSUE THREAD

**Issue by Near-Zhang** [sumory/orange#216]
##### 需求或场景

描述你想实现的功能

##### 使用的插件

针对这个需求你使用了哪个或哪几个插件

##### 具体的配置

rewrite插件中，当to_rewrite变量包含query args

##### 期望的结果

ngx.set_uri_args 提交query args
ngx_set_uri 提交uri 

##### 错误的结果

ngx.set_uri_args 提交query args
ngx_set_uri 却提交 to_rewrite

ngx_set_uri前应该加多一层变量提取：
to_rewrite = string_sub(to_rewrite, 1, from-1)

**Comment by wujunze** [comment]
@Near-Zhang  谢谢反馈  你可以提个 PR  修复一下

**Comment by Near-Zhang** [comment]
#229 我是这样解决的，可以参考修复下

**Comment by wujunze** [comment]
THX @Near-Zhang

**Comment by wujunze** [comment]
已经 fix
