### ISSUE TITLE
网关不能用

### ISSUE THREAD

**Issue by ydd2018** [sumory/orange#218]
你好，
你的端口8888和7777是什么关系，我现在在已经发布了一个api，正常访问地址是hostname:7080/account/v1/customers，
我在URI Rewrite中配置了规则，名称为customers，规则为“单一条件匹配” URI Match “customers”，处理为“hostname:7080/account/v1/customers”

然后我访问hostname:7777/customers，返回404，然后基于customers配置的其他插件也不起作用。

注：因为发布权限的问题，省略了hostname前面的http://

**Comment by Coneboy-k** [comment]
7777 是Orange的api Server，用于第三方的dashboard开发，或者系统数据集成。
 
Rewrite的插件使用，请看下Orange的官网 或者 [lua_nginx系列教程](https://github.com/nblib/notebook/blob/master/lua_nginx%E7%B3%BB%E5%88%97%E6%95%99%E7%A8%8B/%5B11%5Dorange%E6%8F%92%E4%BB%B6%E4%B9%8B%E9%87%8D%E5%86%99%E5%92%8C%E9%87%8D%E5%AE%9A%E5%90%91.md)

**Comment by wangdeyi** [comment]
> 你好，
> 你的端口8888和7777是什么关系，我现在在已经发布了一个api，正常访问地址是hostname:7080/account/v1/customers，
> 我在URI Rewrite中配置了规则，名称为customers，规则为“单一条件匹配” URI Match “customers”，处理为“hostname:7080/account/v1/customers”
> 
> 然后我访问hostname:7777/customers，返回404，然后基于customers配置的其他插件也不起作用。
> 
> 注：因为发布权限的问题，省略了hostname前面的http://

问题解决了没？我也是这种情况
