### ISSUE TITLE
./orange/utils/handle.lua:5: module 'resty.template' not found:

### ISSUE THREAD

**Issue by edagarli** [sumory/orange#22]
➜  orange git:(master) ✗ sh start.sh
start orange..
nginx: [error] [lua] orange.lua:159: init(): Startup error: ./orange/utils/utils.lua:170: ./orange/utils/handle.lua:5: module 'resty.template' not found:
	no field package.preload['resty.template']
	no file '../resty/template.lua'
	no file '/usr/local/lor/resty/template.lua'
	no file '/usr/local/openresty/site/lualib/resty/template.lua'
	no file '/usr/local/openresty/site/lualib/resty/template/init.lua'
	no file '/usr/local/openresty/lualib/resty/template.lua'
	no file '/usr/local/openresty/lualib/resty/template/init.lua'
	no file './resty/template.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/resty/template.lua'
	no file '/usr/local/share/lua/5.1/resty/template.lua'
	no file '/usr/local/share/lua/5.1/resty/template/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/template.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/template/init.lua'
	no file '/usr/local/openresty/site/lualib/resty/template.so'
	no file '/usr/local/openresty/lualib/resty/template.so'
	no file './resty/template.so'
	no file '/usr/local/lib/lua/5.1/resty/template.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/template.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/site/lualib/resty.so'
	no file '/usr/local/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by sumory** [comment]
请参看安装文档，首先安装[lor](https://github.com/sumory/lor)

**Comment by edagarli** [comment]
$ brew tap syhily/lor
$ brew install lor
已经安装，感觉没什么鸟用

**Comment by sumory** [comment]
这个问题的本质是你的Orange找不到lor安装位置。

Orange的nginx.conf文件中配置的lor路径为：

```
lua_package_path '../?.lua;/usr/local/lor/?.lua;;';
```

使用brew安装的lor并不在这个路径，要么你更改lor安装路径，要么你更改nginx.conf

**Comment by edagarli** [comment]
嗯。其实文档里面备注下，不然很容易以外默认路径是nginx配置的

**Comment by edagarli** [comment]
已经好了，不过又出现乱码啦

**Comment by edagarli** [comment]
./dashboard/static/css/application.css" failed (13: Permission denied)

**Comment by edagarli** [comment]
很奇怪，我已经chmod 777了。

**Comment by sumory** [comment]
应该是权限问题，看看你的nginx.conf是否需要使用user指令来配一下

**Comment by edagarli** [comment]
@sumory 问你一句哈，现在按钮不能点击？
<img width="1169" alt="2016-08-25 21 49 32" src="https://cloud.githubusercontent.com/assets/5710228/17971544/d6143c6e-6b0d-11e6-9a3f-e7c631a40402.png">

**Comment by sumory** [comment]
这不是按钮，只是显示规则条数的控件

**Comment by edagarli** [comment]
soga。。不过这设计有点让人误导

**Comment by syhily** [comment]
@edagarli brew 安装的那个需要在package_path 里面指定一下，`brew --prefix lor`的路径。
