### ISSUE TITLE
请问0.7版本啥时候才有空发布？两年多没发新版本了、好期待能合并下发个新版本

### ISSUE THREAD

**Issue by 3zamn** [sumory/orange#223]
请问0.7版本啥时候才有空发布？两年多没发新版本了、好期待能合并下发个新版本。挺好用的网关

**Comment by EasonFeng5870** [comment]
同问。

**Comment by my4381918** [comment]
同问

**Comment by sumory** [comment]
暂时没有精力合并0.7-dev分支，欢迎有兴趣的同学pr或帮忙review

**Comment by wujunze** [comment]
现在我来继续维护这个项目  有兴趣的同学加我微信一起维护

**Comment by wujunze** [comment]
0.7 版本 准备 release  欢迎大家一起来测试

**Comment by wujunze** [comment]
0.7 版本已经发布  https://zhuanlan.zhihu.com/p/61051067
