### ISSUE TITLE
你好  请问有哪些公司的生产环境项目在用 orange  ？

### ISSUE THREAD

**Issue by wujunze** [sumory/orange#224]
你好 
       请问有哪些公司的生产环境项目在用 orange  ？
        例如  什么项目  多少PV  运行了多久

**Comment by sumory** [comment]
- 有一些同学做了微调后在生产使用，但我也不清楚具体生产情况，可以在社区群里问一下
- 社区里有公司二次开发或者优化后投入生产的，比如腾讯游戏、华数传媒等，可以参看今年的[OpenResty大会](http://con.openresty.org/cn/2018/)相关分享
- Orange的设计和实现并不复杂，建议以你具体的场景实测为准，性能热点针对性地优化即可
