### ISSUE TITLE
建议收集

### ISSUE THREAD

**Issue by wujunze** [sumory/orange#226]
**建议收集**

**Comment by we7team** [comment]
建议
1，规则匹配改成hyperscan
2，使用mlcache方案，减少对数据的json处理
3，支持分布式部署，采用redis缓存

**Comment by heixiaoma** [comment]
不知道防火墙的端口，能不能也在web端口进行管理！

**Comment by we7team** [comment]
目前规则的匹配模式不太适用于实际的使用场景，应该改为这样的层级：
第一层：对host的匹配，区分一个个站点
第二层：对站点下一些请求规则的匹配
第三层：一些插件的匹配，比如限速、waf、统计等

**Comment by clearair** [comment]
增加GraphQL支持怎么样？可以配置聚合查询！

**Comment by sumory** [comment]
`对host的匹配，区分一个个站点`，这是kong的做法，之前Orange并没有采用这个做法的原因也说过，如果在最开始就按host切分，那些通用的规则就需要在每个host子流程里再配置一遍，这一点有点废。
如果要打破原来Orange`仅按执行阶段`横向切分的的方式，需要仔细斟酌上面提到的问题，将用户成本减到尽量小。

**Comment by we7team** [comment]
或者有没有更好的方案，既能区分host又能使用通用规则。因为实际的使用场景还是在站点的层级下的。限速、waf等功能还是在匹配规则下的

**Comment by sumory** [comment]
那是因为你是多租户的场景，不是多租户的场景没有那么多`host`来配，几个upstream就足够了，这种情况还要host最优先就很废。

一个纵向、一个横向划分，总有不合适的场景。

要解决这个问题，我建议可以从更高效的`UI`和`API`使用方式上来考虑：
- 如果改为了host优先，那么那些跨host通用的规则是否可以在UI上简单拖拉，或者API简单同步一下就可以适配到所有host
- 现在Orange是采用每个阶段的selector来再做一次细分，这个selector配成host粒度就实现了多租户需求

总结下来就是不管是`host优先`的纵向划分，还是`执行阶段优先`的横向切分，都各有自己的问题。也许抽象出一个`通用规则池`来也能减少部分分歧？仅供参考。

**Comment by azureplus** [comment]
可以参照 kong

**Comment by wujunze** [comment]
> 可以参照 kong

什么地方参考 Kong  ?

**Comment by huangguang93** [comment]
能否增加配置预览(nginx配置格式预览)

**Comment by yyf365** [comment]
生产环境中对密码等敏感信息的管理比较严格。
建议新版本的数据库密码可以密文存储或者使用更高安全方案保存密码

**Comment by luolenny** [comment]
也许可以参考Kong,  支持一下forgerock的OpenAM
https://developer.forgerock.com/docs/platform/how-tos/configuring-kong-use-forgerock-access-management-openid-connect-provider

**Comment by wujunze** [comment]
move to  https://github.com/sumory/orange/issues/250
