### ISSUE TITLE
条件判断模块: 支持的条件提取方式支持Method

### ISSUE THREAD

**Issue by wujunze** [sumory/orange#236]
条件判断模块: 支持的条件提取方式支持Method

**Comment by wujunze** [comment]
@EasonFeng5870

**Comment by EasonFeng5870** [comment]
好的，收到。

**Comment by Near-Zhang** [comment]
@EasonFeng5870 原本就支持的哦，出处参见 orange/orange/utils/condition.lua:95

**Comment by wujunze** [comment]
> @EasonFeng5870 原本就支持的哦，出处参见 orange/orange/utils/condition.lua:95

condition 代码有  UI上没有暴露出来吧

**Comment by EasonFeng5870** [comment]
是的，加上了，发现测试是可用的。

**Comment by wujunze** [comment]
Good Gob 👍  @EasonFeng5870
