### ISSUE TITLE
0.7版本新版里多了几个lua库，但服务器本身是没有的

### ISSUE THREAD

**Issue by delgyd** [sumory/orange#246]
resty.dns.balancer
resty.dns.client
pl.tabelx
前边两个https://github.com/openresty/lua-resty-dns这个里面只有resolver.lua没有其它呀

**Comment by wujunze** [comment]
opm install 即可

**Comment by delgyd** [comment]
[C]: in function 'error'
        /data/webapp/openresty/lualib/pl/path.lua:28: in main chunk
        [C]: in function 'require'
        /data/webapp/openresty/lualib/resty/dns/client.lua:24: in main chunk
        [C]: in function 'require'
        /data/webapp/orange/orange/orange.lua:11: in main chunk
        [C]: in function 'require'
        init_by_lua:2: in main chunk

**Comment by yuewutao** [comment]
一样的，对lor不是太熟

**Comment by delgyd** [comment]
东搞西搞，跑起来了。但有些要报错。uuid偶尔要生成一样的。insert时，无法入库，但不晓得是哪的问题。还在找！

**Comment by wujunze** [comment]
可以把你的配置文件 error 贴出来 大家一起看看

**Comment by wujunze** [comment]
可以把你的配置文件 error log 贴出来  大家一起看看

**Comment by yuewutao** [comment]
nginx: [error] init_by_lua error: /usr/local/orange/orange/orange.lua:11: module 'resty.dns.client' not found:
        no field package.preload['resty.dns.client']
        no file '/usr/local/orange/resty/dns/client.lua'

几个lua找不到，很奇怪，我用opm装还是一样没有

**Comment by delgyd** [comment]
mysql_db.lua:36: query(): bad result: Duplicate entry '70fbfc8d-e8bb-4ea5-b26b-440110242eab' for key 'unique_key': 1062: 23000., client: 192.168.9.1, server: , request: "POST /divide/selectors HTTP/1.1", host: "192.168.9.103:9999", referrer: "http://192.168.9.103:9999/divide"


这里生成的UUID不知道为什么，我这里不管什么时候去操作。。感觉都是这个UUID。没有找到这个UUID是哪生成的，我看了jit-uuid我从里面打出来的好像又不是这个Uuid

**Comment by delgyd** [comment]
> mysql_db.lua:36: query(): bad result: Duplicate entry '70fbfc8d-e8bb-4ea5-b26b-440110242eab' for key 'unique_key': 1062: 23000., client: 192.168.9.1, server: , request: "POST /divide/selectors HTTP/1.1", host: "192.168.9.103:9999", referrer: "http://192.168.9.103:9999/divide"
> 
> 这里生成的UUID不知道为什么，我这里不管什么时候去操作。。感觉都是这个UUID。没有找到这个UUID是哪生成的，我看了jit-uuid我从里面打出来的好像又不是这个Uuid

这个问题，可以肯定和jit-uuid有关，，我用lua-resty-uuid替换这个包。
在utils.lua的
local lruid = require("resty.uuid")

function _M.new_id()
    --return uuid()
    return lruid.generate()
end
把这段换了。。就正常了

**Comment by jacobslei** [comment]
orange start 同样的错误：
[INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf 
nginx: [error] init_by_lua error: /usr/local/orange/orange/orange.lua:11: module 'resty.dns.client' not found:
        no field package.preload['resty.dns.client']
        no file '/usr/local/orange/resty/dns/client.lua'
        no file '/usr/local/lor/resty/dns/client.lua'
        no file '/usr/local/openresty/site/lualib/resty/dns/client.ljbc'
        no file '/usr/local/openresty/site/lualib/resty/dns/client/init.ljbc'
        no file '/usr/local/openresty/lualib/resty/dns/client.ljbc'
        no file '/usr/local/openresty/lualib/resty/dns/client/init.ljbc'
        no file '/usr/local/openresty/site/lualib/resty/dns/client.lua'
        no file '/usr/local/openresty/site/lualib/resty/dns/client/init.lua'
        no file '/usr/local/openresty/lualib/resty/dns/client.lua'
        no file '/usr/local/openresty/lualib/resty/dns/client/init.lua'
        no file './resty/dns/client.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/dns/client.lua'
        no file '/usr/local/share/lua/5.1/resty/dns/client.lua'
        no file '/usr/local/share/lua/5.1/resty/dns/client/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/dns/client.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/dns/client/init.lua'
        no file '/usr/local/openresty/site/lualib/resty/dns/client.so'
        no file '/usr/local/openresty/lualib/resty/dns/client.so'
        no file './resty/dns/client.so'
        no file '/usr/local/lib/lua/5.1/resty/dns/client.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/dns/client.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/usr/local/openresty/site/lualib/resty.so'
        no file '/usr/local/openresty/lualib/resty.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by wujunze** [comment]
缺什么依赖 opm install  即可

**Comment by delgyd** [comment]
> orange start 同样的错误：
> [INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf
> nginx: [error] init_by_lua error: /usr/local/orange/orange/orange.lua:11: module 'resty.dns.client' not found:
> no field package.preload['resty.dns.client']
> no file '/usr/local/orange/resty/dns/client.lua'
> no file '/usr/local/lor/resty/dns/client.lua'
> no file '/usr/local/openresty/site/lualib/resty/dns/client.ljbc'
> no file '/usr/local/openresty/site/lualib/resty/dns/client/init.ljbc'
> no file '/usr/local/openresty/lualib/resty/dns/client.ljbc'
> no file '/usr/local/openresty/lualib/resty/dns/client/init.ljbc'
> no file '/usr/local/openresty/site/lualib/resty/dns/client.lua'
> no file '/usr/local/openresty/site/lualib/resty/dns/client/init.lua'
> no file '/usr/local/openresty/lualib/resty/dns/client.lua'
> no file '/usr/local/openresty/lualib/resty/dns/client/init.lua'
> no file './resty/dns/client.lua'
> no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/dns/client.lua'
> no file '/usr/local/share/lua/5.1/resty/dns/client.lua'
> no file '/usr/local/share/lua/5.1/resty/dns/client/init.lua'
> no file '/usr/local/openresty/luajit/share/lua/5.1/resty/dns/client.lua'
> no file '/usr/local/openresty/luajit/share/lua/5.1/resty/dns/client/init.lua'
> no file '/usr/local/openresty/site/lualib/resty/dns/client.so'
> no file '/usr/local/openresty/lualib/resty/dns/client.so'
> no file './resty/dns/client.so'
> no file '/usr/local/lib/lua/5.1/resty/dns/client.so'
> no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/dns/client.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'
> no file '/usr/local/openresty/site/lualib/resty.so'
> no file '/usr/local/openresty/lualib/resty.so'
> no file './resty.so'
> no file '/usr/local/lib/lua/5.1/resty.so'
> no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'

使用luarocks安装一些第三方库
luarocks install https://luarocks.org/manifests/steved/penlight-1.5.4-1.rockspec
luarocks install https://luarocks.org/manifests/kong/lua-resty-dns-client-2.2.0-1.rockspec
luarocks install https://luarocks.org/lua-resty-http-0.13-0.src.rock
luarocks install https://luarocks.org/manifests/luarocks/luasocket-3.0rc1-2.rockspec

**Comment by EasonFeng5870** [comment]
luarocks install https://luarocks.org/manifests/kong/lua-resty-dns-client-2.2.0-1.rockspec

新版本是不可用的哈，目前是这个版本可以用。

**Comment by JohnnyTTzhu** [comment]
使用 luarocks install https://luarocks.org/manifests/kong/lua-resty-dns-client-2.2.0-1.rockspec正常安装后还是报错。

[INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf 
nginx: [error] init_by_lua error: /usr/local/orange/orange/orange.lua:11: module 'resty.dns.client' not found:
        no field package.preload['resty.dns.client']
        no file '/usr/local/orange/resty/dns/client.lua'
        no file '/usr/local/lor/resty/dns/client.lua'
        no file '/usr/local/openresty/site/lualib/resty/dns/client.lua'
        no file '/usr/local/openresty/site/lualib/resty/dns/client/init.lua'
        no file '/usr/local/openresty/lualib/resty/dns/client.lua'
        no file '/usr/local/openresty/lualib/resty/dns/client/init.lua'
        no file './resty/dns/client.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/resty/dns/client.lua'
        no file '/usr/local/share/lua/5.1/resty/dns/client.lua'
        no file '/usr/local/share/lua/5.1/resty/dns/client/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/dns/client.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/dns/client/init.lua'
        no file '/usr/local/openresty/site/lualib/resty/dns/client.so'
        no file '/usr/local/openresty/lualib/resty/dns/client.so'
        no file './resty/dns/client.so'
        no file '/usr/local/lib/lua/5.1/resty/dns/client.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/dns/client.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/usr/local/openresty/site/lualib/resty.so'
        no file '/usr/local/openresty/lualib/resty.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/orange/orange/orange.lua:11: in main chunk
        [C]: in function 'require'
        init_by_lua:2: in main chunk

**Comment by delgyd** [comment]
> 使用 luarocks install [https://luarocks.org/manifests/kong/lua-resty-dns-client-2.2.0-1.rockspec正常安装后还是报错。](https://luarocks.org/manifests/kong/lua-resty-dns-client-2.2.0-1.rockspec%E6%AD%A3%E5%B8%B8%E5%AE%89%E8%A3%85%E5%90%8E%E8%BF%98%E6%98%AF%E6%8A%A5%E9%94%99%E3%80%82)
> 
> [INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf
> nginx: [error] init_by_lua error: /usr/local/orange/orange/orange.lua:11: module 'resty.dns.client' not found:
> no field package.preload['resty.dns.client']
> no file '/usr/local/orange/resty/dns/client.lua'
> no file '/usr/local/lor/resty/dns/client.lua'
> no file '/usr/local/openresty/site/lualib/resty/dns/client.lua'
> no file '/usr/local/openresty/site/lualib/resty/dns/client/init.lua'
> no file '/usr/local/openresty/lualib/resty/dns/client.lua'
> no file '/usr/local/openresty/lualib/resty/dns/client/init.lua'
> no file './resty/dns/client.lua'
> no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/resty/dns/client.lua'
> no file '/usr/local/share/lua/5.1/resty/dns/client.lua'
> no file '/usr/local/share/lua/5.1/resty/dns/client/init.lua'
> no file '/usr/local/openresty/luajit/share/lua/5.1/resty/dns/client.lua'
> no file '/usr/local/openresty/luajit/share/lua/5.1/resty/dns/client/init.lua'
> no file '/usr/local/openresty/site/lualib/resty/dns/client.so'
> no file '/usr/local/openresty/lualib/resty/dns/client.so'
> no file './resty/dns/client.so'
> no file '/usr/local/lib/lua/5.1/resty/dns/client.so'
> no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/dns/client.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'
> no file '/usr/local/openresty/site/lualib/resty.so'
> no file '/usr/local/openresty/lualib/resty.so'
> no file './resty.so'
> no file '/usr/local/lib/lua/5.1/resty.so'
> no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'
> stack traceback:
> [C]: in function 'require'
> /usr/local/orange/orange/orange.lua:11: in main chunk
> [C]: in function 'require'
> init_by_lua:2: in main chunk

是不是没有装上哟？

**Comment by JohnnyTTzhu** [comment]
@delgyd  嗯嗯，的确是没有装上，用opm的方式重新安装后就好了。
![image](https://user-images.githubusercontent.com/37328576/55945493-7e3b6580-5c7d-11e9-8535-81c4a4888ea2.png)

**Comment by shuaijinchao** [comment]
> resty.dns.balancer
> resty.dns.client
> pl.tabelx
> 前边两个[https://github.com/openresty/lua-resty-dns这个里面只有resolver.lua没有其它呀](https://github.com/openresty/lua-resty-dns%E8%BF%99%E4%B8%AA%E9%87%8C%E9%9D%A2%E5%8F%AA%E6%9C%89resolver.lua%E6%B2%A1%E6%9C%89%E5%85%B6%E5%AE%83%E5%91%80)

进入Orange目录执行`make dependencies`即可安装全部依赖扩展，Orange使用的DNS依赖并不是lua-resty-dns而是lua-resty-dns-client，在Makefile文件第二行对全部Orange的依赖扩展名称和版本都有描述。

**Comment by shuaijinchao** [comment]
Orange使用的lua-resty-dns-client的版本是1.0.0-1，2.x的版本会报错`luarocks install lua-resty-dns-client 1.0.0-1`或者`make dependencies`就可以了

**Comment by EasonFeng5870** [comment]
lua-resty-dns-client 2.2.0 是目前0.7版本最后可用的版本（https://luarocks.org/modules/kong/lua-resty-dns-client）

**Comment by huangguang93** [comment]
想问下怎么用opm命令安装lua-resty-dns-client吗? 新手请教下大家~

**Comment by cmdares** [comment]
同问！的确搞不定！
# opm search dns
openresty/lua-resty-dns                           Lua DNS resolver for the ngx_lua based on the cosocket API
jkeys089/lua-resty-resolver                       Caching DNS resolver for ngx_lua and LuaJIT
通过命令行检索仓库中，没有所谓的“lua-resty-dns-client”
怎么安装？
@JohnnyTTzhu @delgyd

**Comment by cmdares** [comment]
一通折腾，各种依赖，
先注释掉lua-resty-dns-client 看看能启动否，发现又引入这个东西解决pl.tabelx
https://github.com/stevedonovan/Penlight/tree/master/lua/pl
安装后，发现
nginx: [error] [lua] orange.lua:75: init(): Startup error: /usr/local/orange/orange/utils/utils.lua:192: .            /pl/path.lua:28: pl.path requires LuaFileSystem

pl/path.lua 继续却类库
    link_attrib = lfs.symlinkattributes
else
    error("pl.path requires LuaFileSystem")
end

luarocks install luafilesystem
opm install spacewander/luafilesystem
再次执行 orange start 依旧报错，不知到怎么办了
lua库的地方就一大堆
/usr/share/lua/5.1
/usr/local/openresty/lualib/
/usr/local/orange/orange/lib/
包管理 2个omp和luarocks
总之折腾的懵圈了！
我的系统是centos7 虚拟机，能否同学们给个正确的安装教程（命令行方式）
主要是最后orange start 最后这一步的各种报错，咋整。
网上的一篇教程写的非常细致：但是是0.6版本。https://www.jianshu.com/p/03e6dc6a904b
这0.7版本的最后一步就这么费劲！

**Comment by sumory** [comment]
我看大家在库的安装上都费了很多劲儿(0.6及之前的版本就在尽量避免这个问题)，现在OR的包管理方案确实都不完美，@wujunze 是否可以考虑这两个方案:
- Orange仓库里引入3rd_party的包，将这些依赖的稳定版本全部下载到这个目录，随Orange的发布和升级
- 在OPM单独建一个Orange使用的3rd_party包，将所有外部依赖全统一拷贝进去，然后Orange安装脚本里仅通过OPM来安装

**Comment by wujunze** [comment]
在OPM单独建一个Orange使用的3rd_party包，将所有外部依赖全统一拷贝进去，然后Orange安装脚本里仅通过OPM来安装

这个方案可行

**Comment by cmdares** [comment]
期待，那就先不折腾了，等待规范化动作。感谢。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by huangguang93** [comment]
期待引入第三方包，减少安装的复杂度，目前还是用的0.6版本

**Comment by wujunze** [comment]
fixed   https://github.com/sumory/orange/pull/271

**已经修正**
大家按照最新的 REAME 文档安装即可

**Comment by xinlanforeverk** [comment]
可参考以下的安装方法：
https://github.com/xinlanforeverk/orange_install/blob/master/README.md
