### ISSUE TITLE
启动报错问题

### ISSUE THREAD

**Issue by Lyaoer** [sumory/orange#262]
##### 使用的Orange版本

v0.7.0

##### 需求或场景

搭建环境并启动orange

##### 具体的配置

使用了https://github.com/syhily/docker-orange/blob/master/Dockerfile

##### 期望的结果

期望正常启动

##### 错误的结果

![TIM图片20190424181929](https://user-images.githubusercontent.com/30254858/56652276-92d81e80-66bd-11e9-8f8a-ff6adf1c2037.png)
orange/orange.lua的第11行local dns_client = require("resty.dns.client")没有看到所需的文件

**Comment by jiangwh** [comment]
![image](https://user-images.githubusercontent.com/2804801/56716765-b78bcf00-676d-11e9-8182-02e4ba6098b1.png)
1、master分支代码存在问题。

**Comment by wujunze** [comment]
感谢反馈 
Orange 开发组 正在解决中   @Near-Zhang 
会把所有的依赖打包成一个 opm 包  方便大家部署安装

**Comment by cmdares** [comment]
+1 期待

**Comment by wujunze** [comment]
fixed https://github.com/sumory/orange/pull/271
