### ISSUE TITLE
Orange 网关API在鉴权的时候怎么通过访问数据库来做验证

### ISSUE THREAD

**Issue by lxpanghuang** [sumory/orange#264]
##### 使用的Orange版本

v0.6.4

##### 需求或场景

开启一个基本的鉴权插件，也新增一个规则。想要实现的功能是，在用户访问网关时，通过变量提取木板提取header里面的的参数去访问数据库做些判断。这个要怎么做呢

##### 使用的插件

HTTP Basic Auth

##### 具体的配置

![image](https://user-images.githubusercontent.com/40419417/57212434-41615500-7016-11e9-8773-dc94bf307fbd.png)

规则是假如访问网关的请求中header中username参数不等于xiaoming则跳到401页面

##### 期望的结果

期望是能取得username参数访问数据库做判断

##### 错误的结果

描述实际的结果，比如错误的输出或截图

**Comment by wujunze** [comment]
这个可能需要你二次开发一下插件  或者提供一个登陆鉴权的接口   修改一下鉴权插件就可以满足你的需求
