### ISSUE TITLE
nginx多个worker时是不是会重复执行load_data_by_mysql

### ISSUE THREAD

**Issue by sunyq** [sumory/orange#265]
##### 使用的Orange版本

如v0.7.0

阅读源码的时候看到`Orange.init_worker()`中调用了`dao.load_data_by_mysql(store, v)`
想问一下，如果nginx的worker进程数量多于一个时，应该是每个worker都会执行一遍`load_data_by_mysql`吧？
所以，内存中的配置其实是会加载多次(后生成的worker会把前面worker初始化的配置刷新覆盖？)

**Comment by sumory** [comment]
本来是只有worker0加载，后来好像是 @noname007 提了个pr改成了每个都加载一次，貌似是为了兼容某些版本无法获取woker号的问题

**Comment by sunyq** [comment]
ok.
重复加载在流量比较高的情况下，会有什么问题么？
会不会出现一种情况：
一个worker还在更新配置内容，然后就有其他worker要读取里面的内容？
我看了下OpenResty文档里只说set,get这些操作是原子性的

**Comment by sumory** [comment]
极端情况应该会有风险，这个可以跟之后的配置存取优化(json序列化)一块考虑 @wujunze ，比如每个worker或module独享一份配置缓存，然后用一定的策略(定时器或外部显式触发)来更新

**Comment by sunyq** [comment]
好的，感谢！
