### ISSUE TITLE
nginx: [emerg] unknown directive "lua_package_path"

### ISSUE THREAD

**Issue by msgcode** [sumory/orange#266]
启动报错: nginx: [emerg] unknown directive "lua_package_path" in /usr/local/orange/conf/nginx.conf:45

orange -v => 0.7.0
openresty -v => openresty/1.15.8.1
lua -v => Lua 5.1
luajit -v => LuaJIT 2.1.0-beta3

**Comment by wujunze** [comment]
在你的 nginx.conf  添加这个指令  lua_package_path
