### ISSUE TITLE
master分支两个不完美的地方

### ISSUE THREAD

**Issue by msgcode** [sumory/orange#268]
1. handler.lua:51 
    [scheme] 应该是拼错了? 应该是[schema] ? 所以一直都是nil

2. handler.lua:103  
    ngx.var.target 是不存在的~ 应该在nginx  api-server location / 下加上 set $target '';

**Comment by wujunze** [comment]
@msgcode  谢谢反馈 收到    你如果有兴趣可以提个 PR

**Comment by msgcode** [comment]
好的~
