### ISSUE TITLE
我想实现反向代理的时候能够实现upstream和host动态上下线

### ISSUE THREAD

**Issue by hoseazhai** [sumory/orange#272]
针对`Orange使用`的提问，对于简单几句话描述不清的问题，请使用以下格式，不符合格式或描述含糊不清的issue将不予回复。根据问题模板填写好后，提问之前请去除模板的无用内容。

##### 使用的Orange版本

v0.7.0

##### 需求或场景
我想实现反向代理的时候能够实现upstream和host动态上下线

##### 使用的插件

动态负载 和balancer

##### 具体的配置

balancer
![image](https://user-images.githubusercontent.com/24357698/58770995-8318f780-85e4-11e9-8a32-fefba37c12f9.png)
动态负载
![image](https://user-images.githubusercontent.com/24357698/58771025-a0e65c80-85e4-11e9-984d-1977317abd17.png)

##### 期望的结果

希望upstream和host动态上下线

##### 错误的结果

发现只能选择nginx.conf里面配置的upstream，无法加载balancer里面配置

**Comment by lyyoung** [comment]
最后怎么解决的
