### ISSUE TITLE
最新的提交中有代码错误，启动的时候会报错

### ISSUE THREAD

**Issue by minchina** [sumory/orange#273]
##### 使用的Orange版本

如v0.7.0

##### 需求或场景
安装完成之后 ，运行start.sh会报错。
应该是 c19319ed4709faa8a8f这次提交的代码注释写的有问题。
![VXA PCIVWY_PG0EZ%1Y2EMI](https://user-images.githubusercontent.com/7325429/58942674-caec7a00-87b0-11e9-8577-28ef33baae7c.png)

**Comment by zhangbao0325** [comment]
最新的提交中没有更改代码，只是提供了一个opm包来下载所orange的第三方包，并完善了一下README.md文档。您的具体报错是什么？

**Comment by wujunze** [comment]
fixed https://github.com/sumory/orange/pull/274  
Thanks  @zhangbao0325    @minchina
