### ISSUE TITLE
ピラフ様、イベントのトリガー処理を提供してお願いします！

### ISSUE THREAD

**Issue by shengnoah** [sumory/orange#28]
新WAFの機能：攻撃がある場合、についてはルールとイベント中にIPデータを提供するしてください、または、バッチファイル実行のインターフェースがある、良いですよ。

以上

**Comment by sumory** [comment]
would you please describe this issue in english?

**Comment by shengnoah** [comment]
@sumory さん、ごめんなさい、 英語はできません、中国語できます。

**Comment by cch123** [comment]
please provide event trigger
when face with attack, can provide rule and ip which trigger event，or， provide patch file interface which will be nice

**Comment by syhily** [comment]
![68747470733a2f2f7777332e73696e61696d672e636e2f6c617267652f303036744e633739677731666239306470306637746a33306b30306d666a74322e6a7067](https://cloud.githubusercontent.com/assets/1761698/21760133/aadc9a40-d684-11e6-8d3a-b6df8d473f05.jpeg)

**Comment by sumory** [comment]
patch is welcome! official support for this feature will be considered later.

**Comment by cch123** [comment]
just translation, orz

**Comment by wujunze** [comment]
@shengnoah 你是中国人  为什么要用日语来提issue ?
