### ISSUE TITLE
关于dashboard的2点改进意见

### ISSUE THREAD

**Issue by lhmwzy** [sumory/orange#30]
1、全局统计中的address应为服务器的IP地址，不应该是IP地址和端口号
2、uptime应该为持续运行时间，不应该是启动时的那个时刻时间

**Comment by syhily** [comment]
uptime 计算启动的时间戳没啥问题，到时候前端 js 运算一下就好。

**Comment by sumory** [comment]
Considered it done with pr[#34](https://github.com/sumory/orange/pull/34) and [#31](https://github.com/sumory/orange/pull/31)
