### ISSUE TITLE
集群部署问题

### ISSUE THREAD

**Issue by coder-zhuyu** [sumory/orange#41]
目前支持集群部署吗？我研究了下，好像一些限制都是基于单机的

**Comment by sumory** [comment]
Orange暂时只提供很简单的集群功能，并不支持自动更新集群配置，但可通过调用API或者手动同步。

集群间共享的数据只有存储在MySQL里的配置信息，在一个节点修改过配置后，可以通过以下三种方式同步其他节点：

- 通过在其他节点上的Dashboard里触发“同步配置”
- 通过调用其他节点上的API
- 重启其它节点

**Comment by coder-zhuyu** [comment]
目前的限速应该是只针对单个节点的吧

**Comment by sumory** [comment]
是的，也可以很简单的改到redis来支持集群。目前只有这一个插件“需要”redis，当时为了不增加复杂性，所以还没有在Orange引入redis依赖。

**Comment by coder-zhuyu** [comment]
恩，谢谢

**Comment by coder-zhuyu** [comment]
是否考虑把shared dict里面的规则放到lua table里面，减少每次解析json的操作

**Comment by sumory** [comment]
@coder-zhuyu 

- 这一点有考虑，因为频繁的json序列化还是浪费了一些性能的。
- 但会引入一个问题就是修改规则后多个worker间的数据通信（module级别的lua table是worker级别的），在一个worker里改了后要让其他worker同事修改并保证修改成功。
- 目前能想到的更新数据的方式有
    - 每个worker起一个协程定时监控信号(可以是shared dict里的某个标识)，当来信号时从存储配置的shared dict拉数据更新worker内的配置(lua table)
    - 通过外面添加一个redis，每个worker订阅redis来更新内部配置

但这两种更新数据的方式在我看来还都不够优雅，所以也就没实现这部分逻辑。

**Comment by syhily** [comment]
https://github.com/sumory/orange/issues/5

**Comment by coder-zhuyu** [comment]
好的，谢谢
