### ISSUE TITLE
Add .editorconfig for uniform code style 

### ISSUE THREAD

**Issue by syhily** [sumory/orange#44]
- [ ] Base code style discuss @sumory
- [ ] Generate `.editorconfig` file
- [ ] Wiki or document for introduce how to apply our code style.

**Comment by sumory** [comment]
done with this commit #[3fa2ee](https://github.com/sumory/orange/commit/3fa2eeb0e468375c475700567c7c726ef1e788f1)

**Comment by syhily** [comment]
Yeah, a cool job. But need more document on configuration.
