### ISSUE TITLE
配置多个选择器，多个规则，性能问题

### ISSUE THREAD

**Issue by lhyfree** [sumory/orange#46]
经我们测试发现：
1.重写选择器配置多个，请求全部匹配
2.分流选择器配置多个，匹配后会跳出

我们选择器都是配置的url  match，这样就都是是通过正则匹配的。
然后每个选择器又有多个规则，也是url match，也要正则匹配。

1.这样策略一多，每个请求就经过了很多 正则匹配， 是否会很损耗性能？

2.如果选择器只配一个，用全流量方式， 只在规则那匹配，这样会少了很多正则匹配，相对上面性能是否会好一些?

=============
我们有对orange做ab压测，发现相比openresty，未开启分流损耗性能20%，开启一条分流策略，性能损耗30%。

很担心选择器和规则过多，又都是正则匹配，性能会很差。

请问 你那边有相关的性能数据吗？   规则过多有什么好的优化方式？  
我们打算选择器只用一个全流量。

谢谢！

**Comment by sumory** [comment]
1. 选择器的配置中有一项”继续后续选择器“的选项，不选的话经过当前选择器匹配后就不再继续匹配后续选择器
2. 分流的逻辑就是如此，当命中到一个分流规则后就是应该跳出后面所有的”选择器“和”规则“了

如果是共同的规则判断建议放在选择器里，在选择器里已经判断的，就无需再在这个选择器的规则里再判断了；
正则表达式相对其他判断是比较费，如果能使用=、!=、>、<这样的判断的就尽量用这种判断；
规则过多时你应该仔细规划怎么使用”选择器“和”规则“；
我没有给出统一的性能测试，因为没有意义，使用场景千差万别，不同的配置会导致不同的性能，你应该根据你实际的应用做好测试，就比如你用了非常多规则，用了非常多正则，那性能肯定会下降比较多。

**Comment by syhily** [comment]
Benchmark test need.

**Comment by yuchangyang** [comment]
能有个基本的性压测数据参考最好了，可以作为方案选择时的重要依据。
楼上所说的“**1.重写选择器配置多个，请求全部匹配**” ，我细读了一下
源码应该是与handle.lua所使用的 “ngx_set_uri(to_rewrite, **true**)  ”指令
有相关，true代表last指令，false代表break;  可以查看一下nginx rewrite的
last/break的区别就明白了，可以根据业务情况来修改。

**Comment by sumory** [comment]
我后续造几个比较典型的应用场景压一份数据吧，除此之外，还是建议用户自己根据编写的规则做好测试，知晓瓶颈在哪里。

**Comment by lhyfree** [comment]
谢谢回复。

本打算用多台orange组成集群，维护一份配置，作为所有系统的统一网关，因各系统的nginx都有自己差异的配置，所以造成了会在orange设置很多选择器和规则。

不知道贵公司是否有这样的应用场景？

还是说不同系统维护不同配置的orange，做成一个个的小orange集群？

希望能给予一下生产应用的建议，谢谢。

**Comment by sumory** [comment]
- 维护一个nginx集群就好，你们目前有几个nginx节点就维护几个orange节点
- 你说的“很多选择器”是指的你有很多子域？可以每个子域给定一个选择器（使用域名/host作为判断依据），这个选择器内部的规则就是只属于这个域的规则，这样能减轻多个域间不必要的判断
- orange默认给每个请求响应头都注入了`X-Orange-Proxy-Latency`和`X-Orange-Upstream-Latency`来指明这次请求分别在网关、real server上的耗时
- 配置好后，建议针对典型请求路径做下压测，对整体性能有个把握

**Comment by luckybean** [comment]
实践小结：
各个插件的 选择器，如果选择 “略过后续选择器”，则不管当前规则匹配是否成功，都会停止后续选择器的匹配，所以 选择器 只好选择 “继续后续选择器”。
对于 monitor 插件，规则里面可以选择 “继续匹配”或者“停止匹配”。“继续匹配”表示当前规则匹配成功后，还会继续匹配后续的选择器和规则；“停止匹配”表示一旦当前规则匹配成功，则停止匹配后续的选择器和规则。
对于 rewrite 插件，规则的默认处理方式等同于rewrite last，因为代码里用的是ngx_set_uri(to_rewrite, true)；如果想只匹配1次，也就是rewrite break的效果，可以把代码改为ngx_set_uri(to_rewrite, **false**)。
对于 devide 插件，规则默认就是匹配成功则停止后续匹配。
从压测来看，选择器和规则的匹配比较消耗CPU，就算只把rewrite插件改成rewrite break的效果，也能提升40%左右的性能。

**Comment by sumory** [comment]
👍 很详细的总结

> 从压测来看，选择器和规则的匹配比较消耗CPU，就算只把rewrite插件改成rewrite break的效果，也能提升40%左右的性能。

这一点应该是符合预期的，Orange有很多时间都花在配置的序列化上；这里单纯的一条rewrite break指令相比于Orange要串联下文(执行了很多lua代码)当然会节省很多。

> 如果想只匹配1次，也就是rewrite break的效果

欢迎PR来增加`break`或`last`等配置 :)

**Comment by luckybean** [comment]
提升40%，是从5000提高到7000，但提升更多的，是修改_M.get_json。从火焰图来看，差不多50%的CPU消耗在decode方法。我做了个实验，把_M.get_json封装到单独的lua文件，require加载进来，这样每个worker只加载一次，并把decode后的结果保存起来，而不是每个请求进来时都反复的decode。改完再测，性能可以再提升一倍。

**Comment by sumory** [comment]
热代码提升几倍都是可以预期的，这一点毋庸置疑(单核10条规则我测过8000 QPS，但做module缓存可以到1.2W+)，另外绑定CPU也有约20%的提升。

我也反复提到过，序列化以及请求级别的存取shard dict都会耗费大量性能。存在shared dict里的配置都可以在vm级别做module缓存，但是数据的更新要做到可感知，这又退化到worker间通信的问题。

目前没有我认为的非常优雅的来解决这个问题的方式。

**Comment by luckybean** [comment]
module里用一个变量_M.needUpdate记录是否需要重新用get_json decode规则数据，通过API更新数据时，更新变量_M.needUpdate，然后在redirect阶段先根据_M.needUpdate判断是否需要更新数据。只在第一个请求时decode规则数据，数据没有变动时，decode数据直接使用module缓存里的，数据更新时redirect阶段再decode一次。这个方式如何？

**Comment by sumory** [comment]
- 这个机制最好做到与现有插件无关，而且能够在API更新失败时能反馈出来

**Comment by sumory** [comment]
- 这个机制最好不要耦合在现有的任一个插件里，而且能够在API更新失败时能反馈出来
- module里的数据是worker级别的，仍然需要解决的跨worker消息同步

**Comment by syhily** [comment]
* 第一个是跨Worker共享Module解析上下文问题。
* 关于插件数据解析问题，我个人觉得，是否可以考虑上PG一类的直接存储JSON格式呢？

**Comment by sumory** [comment]
至于用pg还是mysql还是任意其它数据源保存json都没有根本上的差异

**Comment by luckybean** [comment]
每个worker对应shared dict里的一条记录，以ngx.worker.id()区分是哪个worker，API更新了规则数据，shared dict里相应的记录标记为需要更新，worker里根据shared dict的值判断是否需要再次decode数据。需要改动的地方也不涉及到现有插件，如何？

**Comment by sumory** [comment]
可

**Comment by luckybean** [comment]
我的环境配置有30个选择器，30条规则，4core机器，TPS从5000提升到15000，其中最有效的尝试就是减少cjson的decode，提升了差不多7000。

**Comment by luckybean** [comment]
我自己的实践发现：通过减少cjson的decode，TPS从7000提升了14000。
