### ISSUE TITLE
dashboard首页500错误

### ISSUE THREAD

**Issue by lhyfree** [sumory/orange#47]
dashboard首页在orange跑一段时间后就会出现500错误。

![o1](https://cloud.githubusercontent.com/assets/4714407/21298667/e909e050-c5ce-11e6-8e0d-60e2f4737d7f.png)

错误日志：
2016/12/19 09:47:19 [error] 28429#0: *195 [lua] server.lua:72: fn(): /usr/local/orange/dashboard/routes/dashboard.lua:74: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	/usr/local/lor/lor/lib/router/layer.lua:120: in function </usr/local/lor/lor/lib/router/layer.lua:119>
	[C]: in function 'ipairs'
	/usr/local/orange/dashboard/routes/dashboard.lua:74: in function 'fn'
	/usr/local/lor/lor/lib/router/layer.lua:118: in function </usr/local/lor/lor/lib/router/layer.lua:117>
	[C]: in function 'xpcall'
	/usr/local/lor/lor/lib/router/layer.lua:117: in function 'handle_request'
	/usr/local/lor/lor/lib/router/route.lua:93: in function 'next'
	/usr/local/lor/lor/lib/router/route.lua:97: in function 'fn'
	/usr/local/lor/lor/lib/router/layer.lua:118: in function </usr/local/lor/lor/lib/router/layer.lua:117>
	[C]: in function 'xpcall'
	/usr/local/lor/lor/lib/router/layer.lua:117: in function 'handle_request'
	/usr/local/lor/lor/lib/router/router.lua:194: in function 'next'
	/usr/local/lor/lor/lib/router/router.lua:214: in function 'fn'
	/usr/local/lor/lor/lib/router/layer.lua:118: in function </usr/local/lor/lor/lib/router/layer.lua:117>
	[C]: in function 'xpcall'
	/usr/local/lor/lor/lib/router/layer.lua:117: in function 'handle_request'
	/usr/local/lor/lor/lib/router/router.lua:205: in function 'next'
	/usr/local/lor/lor/lib/router/router.lua:214: in function 'handle'
	/usr/local/lor/lor/lib/application.lua:95: in function 'handle'
	/usr/local/lor/lor/lib/application.lua:54: in function 'run'
	content_by_lua(dashboard.conf:28):4: in function <content_by_lua(dashboard.conf:28):1>,

**Comment by sumory** [comment]
fixed with commit [#f4c94e](https://github.com/sumory/orange/commit/f4c94e04ac198f02ad8b3cc024143b8a5470da0a)

**Comment by lhyfree** [comment]
看你修改的代码是对 selector_rules  做了判断。

想问一下为什么selector_rules会在运行一段时间后，就取不到数据了？

是否意味着共享内存里的规则 在运行过程中会有丢失的情况？

**Comment by sumory** [comment]
运行时程序自己不会删除规则，可能是你手动删除了某些规则。我不太清楚你的具体的场景。也有可能是个bug，但我这边无法复现出来。

**Comment by lhyfree** [comment]
我复现了这个bug，

在任一插件下，新建一个选择器，但选择器里不创建任何规则。再点击概况就会unknown error。

**Comment by lhyfree** [comment]
在  **选择器启用，且选择器里没有任何规则的情况下**，就会出现此种情况。

**Comment by sumory** [comment]
我之前提交的commit#f4c94e应该可以修复这个问题
