### ISSUE TITLE
Use serf to update cluster's configuration cache, and easy monitor

### ISSUE THREAD

**Issue by syhily** [sumory/orange#5]
Intro: https://www.serfdom.io/intro

Let's introduce a new sync flow for orange cluster.

Modify (plugin configuration) -> Test (Passed) -> Push to Data Store (MySQL) -> Notify to all orange cluster (using serf) -> Pull configuration from DB.

**Rule**
1. Any modification will not save to database directly in case of misconfiguration.
2. Configuration mainly stored and read from SHM except initialization.
3. After successfully push to database orange should notify its child node to pull updation by using serf.
4. Manual update operation should not be replaced by this auto sync flow.

**Comment by sumory** [comment]
no plan for `serf` support.
