### ISSUE TITLE
orange.store.dao模块的load_data_by_mysql函数中记录日志的级别建议为ngx.INFO

### ISSUE THREAD

**Issue by shixinke** [sumory/orange#52]
oad_data_by_mysql函数中，init_enable_of_plugin初始化插件为true时l记录日志的级别建议为ngx.INFO，代码大致为512,522行

**Comment by sumory** [comment]
基于什么考虑要改为INFO? 初始化数据是很重要的步骤，所以不管对错都需要有明确的反馈。
