### ISSUE TITLE
Many routes under `monitor` has been lost since v0.6

### ISSUE THREAD

**Issue by spacewander** [sumory/orange#55]
https://github.com/sumory/orange/blob/master/orange/plugins/monitor/api.lua:
There used to be 8 routes, but now only `/monitor/stat` left over.

It seems more like a bug instead of api change...

**Comment by sumory** [comment]
`api:merge_apis(common_api("monitor"))` was used to expose the other common APIs.

**Comment by spacewander** [comment]
Got it. Thanks.

**Comment by spacewander** [comment]
I dug deeper, but could not find where to enable some routes described in docs. 
Maybe those routes are really lost...

```
$ curl localhost:7777/monitor/configs
{"msg":"404! sorry, not found.","success":false}
```

**Comment by sumory** [comment]
the documents are not compatible with version beyond 0.6.0 for now.
