### ISSUE TITLE
dashboard 用户的密码生成规则是什么？？？

### ISSUE THREAD

**Issue by sylerly** [sumory/orange#57]
看数据库 里插入的那条默认数据是64位的，问题是dashboard里没有用户管理，那么我要新增一个用户的时候，密码怎么计算出来？？？

**Comment by sumory** [comment]
有用户管理，用默认账户登进去的管理员就是超级管理员

**Comment by noname007** [comment]
@sylerly 这里面没有做用户权限的分级。

**Comment by noname007** [comment]
@sumory 我感觉其实是可以做个用户权限的分级的。基于rbac 规则。

**Comment by sumory** [comment]
rbac模型对于Orange来说太重了，一个简单的能控制基本权限的策略够用就好，毕竟系统本身的权限管理不是Orange的侧重点
