### ISSUE TITLE
是否支持淘宝的tengine？

### ISSUE THREAD

**Issue by wenly2014** [sumory/orange#59]
如题

**Comment by sumory** [comment]
理论上只要支持ngx_lua就可以

**Comment by spacewander** [comment]
tengine 附带的 lua-nginx-module 版本比较低，不支持 `*_block` 指令。所以要用的话，需要自己编译 lua-nginx-module。

**Comment by spacewander** [comment]
另外如果要基于 tengine 编译 lua-nginx-module，需要从 master 上拉代码编译。最新发布的版本并不支持< 1.9 的 Nginx 版本（参见 https://github.com/openresty/lua-nginx-module/commit/5e59e8c897c4256dc14bdd7f1b2f0b8d090a9434）
