### ISSUE TITLE
关于rewrite的问题

### ISSUE THREAD

**Issue by westonlv** [sumory/orange#60]
我的请求是这样的`http://hostA/orange/say/hello`, 我想通过rewrite模块将url地址重写成`http://hostB/say/hello`,（hostA变成hostB，并且去掉orange），但是我在配置了rewrite之后一直是404，后来看了代码发现orange的urlrewrite功能并不能改变host，我的变量提取配置的是(orange)，处理配置的是${1}，请问下orange的重定向是否无法满足我的这种需求？？或者有其他的组合配置方式？

**Comment by sumory** [comment]
首先要区分“重定向（redirect）”和“重写（rewrite）”这两个概念。
改变host请使用重定向插件，重写插件应用于只改变uri的场景。

**Comment by jsszlws** [comment]
![1](https://cloud.githubusercontent.com/assets/9129314/23008967/2c6d776e-f44e-11e6-8a60-e9c3a79d917f.jpg)
我想我描述的可能不太好，如上图，orange和真实站点服务器是在两台护物理机器上，orange服务器地址为：192.168.1.111，站点服务器在192.168.1.222，当我访问了http://192.168.1.111/orange/say/hello的时候orange的rewrite插件会重写/orange/say/hello，变成/orange，所以最终访问的url地址变成为：http://192.168.1.111/orange/，而不是我想要的http://192.168.1.222/say/hello，麻烦看请下我诉求哦。

**Comment by jsszlws** [comment]
我刚才试了这样的方案，如图：
![1](https://cloud.githubusercontent.com/assets/9129314/23009494/334a8f9c-f451-11e6-954b-8e7c75c89df2.png)
1、我改写了获取重写的uri规则，按照orange的算法应该是正则匹配到的那个uri作为重写后的uri，但是我需要的是出去正则匹配到，上面是先写死测试用
2、然后我在分流插件中配置了分流策略，按照orange策略，接下来应该是走分流插件，这样让服务端重新在orange内部能够匹配到分流后的uri（/say/hello）对应的策略，就能够路由到对应的站点了。
希望指点下是否为最佳方案？？？是否有更好的建议？

**Comment by sumory** [comment]
两种方案：

1. 使用redirect插件

- 在`变量提取模块`里使用正则表达式从uri中提取出`/say/hello`
- 在配置url的时候使用上一步提取出的值拼到新的url上

即可实现原始请求`http://192.168.1.111/orange/say/hello`重定向到`http://192.168.1.222/say/hello`

2. 使用rewrite插件

- 在nginx.conf里建了一个upstream指向`192.168.1.222`
- 在`变量提取模块`里使用正则表达式从uri中提取出`/say/hello`
- 在配置**uri**的时候使用第一步的upstream名称和第二步提取出的`/say/hello`拼到新的要rewrite到的uri上

这两种方案都可以，具体需要你自己试试

**Comment by jsszlws** [comment]
其实我的uri除了/orange是不变的，其他都有可能会变
但是我大概知道应用用什么方式去做了

**Comment by jsszlws** [comment]
我配置了upstream，然后配置rewrite插件的时候，把处理配置成upstream地址，但是404，我看了报错信息是：
2017/02/16 07:27:19 [error] 5468#5468: *7 open() "/usr/local/orange/htmlhttp://default_upstream/say/hello" failed (2: No such file or directory),

**Comment by westonlv** [comment]
这个问题能帮忙回答下吗？

**Comment by sumory** [comment]
你的upstream叫`default_upstream`？

**Comment by westonlv** [comment]
是的呢，但是前面多了/usr/local/orange/html这个静态目录，感觉有问题？

**Comment by sumory** [comment]
贴配置图，这样描述我猜不到你到底哪里错了，还有最好是你自己多尝试下

**Comment by westonlv** [comment]
你能否给个rewrite的完整的详细的案例啊？这样我可以照着配置一遍。

**Comment by westonlv** [comment]
@sumory

**Comment by sumory** [comment]
重定向规则配置：
![image](https://cloud.githubusercontent.com/assets/1326893/23151726/10b5c948-f838-11e6-9a8a-521ddc7c0908.png)

nginx.conf中相关配置：

```
upstream default_upstream {
        server localhost:8001;
}
server {
        listen 8001;
        server_name localhost 127.0.0.1;
        access_log ./logs/default_upstream_access.log main;
        error_log ./logs/default_upstream_error.log;

        location / {
            content_by_lua_block {
                ngx.say([[Hello! this is default upstream, uri:]] .. ngx.var.uri)
            }
        }
    }
```

之后访问`http://localhost/abc/123`出现以下响应，表示规则配置成功

![image](https://cloud.githubusercontent.com/assets/1326893/23151786/62814b26-f838-11e6-9678-36577b6c40a3.png)


**PS**: 只能帮你到这儿了，建议你自己多尝试，原理和使用都很简单，这样解决问题的效率会高一些

**Comment by westonlv** [comment]
其实这一步我也实现，是后面页面跳转的时候有问题，如果作者注意看下我上面贴出来的错误日志就可以看出来多了/usr/local/orange/html

**Comment by sumory** [comment]
请你仔细看我给你的贴图，我解决的就是你这个`多了/usr/local/orange/html`的问题！

**Comment by noname007** [comment]
我怎么感觉这个应该用分流插件，不是rewrite 插件。 ：-（
