### ISSUE TITLE
post请求怎么重定向或者代理？

### ISSUE THREAD

**Issue by phphappy** [sumory/orange#61]
使用post请求的化，重定向不允许，使用代理的化，没法接收post请求的参数。请问怎么处理？
使用nginx的反向代理可以用post请求，在orange怎么配置反向代理？

**Comment by jsszlws** [comment]
orange里面的分流插件

**Comment by phphappy** [comment]
已经使用分流插件，但是接口报post参数错误.不知道分流插件怎么配置请求参数

**Comment by westonlv** [comment]
看下你的配置和错误信息？

**Comment by sumory** [comment]
consider it resolved
