### ISSUE TITLE
依赖lor0.3.0dashboard无法显示页面

### ISSUE THREAD

**Issue by westonlv** [sumory/orange#62]
如题，这时候恢复lor到0.2.6的时候能够正常访问，希望作者兼容下

**Comment by sumory** [comment]
Orange目前只支持lor v0.2.*版本，先不要急着升级，兼容之后我会发布新版本。
如果急用请参考lor升级文档[从0.2.*迁移到0.3.0版本(http://lor.sumory.com/migration)

**Comment by westonlv** [comment]
我想在windows上测试我的项目，这样就不用部署到服务器上测试了？orange能支持windows环境吗？

**Comment by sumory** [comment]
没有在windows上测试过，不保证兼容性

**Comment by sumory** [comment]
[Orange v0.6.2](https://github.com/sumory/orange/releases/tag/v0.6.2)版本已经可以兼容lor v0.3.0
