### ISSUE TITLE
env: resty: No such file or directory？

### ISSUE THREAD

**Issue by edagarli** [sumory/orange#63]
justhacker:orange jhp$ sudo make install
Orange installed.
env: resty: No such file or directory
make: *** [install] Error 127
justhacker:orange jhp$

**Comment by edagarli** [comment]
我mac编译openresty的时候是带有
sudo ./configure --with-luajit --without-http_redis2_module --with-http_stub_status_module --with-http_iconv_module --with-cc-opt="-I/usr/local/opt/openssl/include/ -I/usr/local/opt/pcre/include/" --with-ld-opt="-L/usr/local/opt/openssl/lib/ -L/usr/local/opt/pcre/lib/" -j8

**Comment by sumory** [comment]
Orange提供的默认脚本以及orange cli工具依赖resty和nginx命令， resty和nginx命令都是在安装OpenResty时安装的， 如果使用过程中提示找不到， 应该将这两个命令加入到环境变量中。

**Comment by edagarli** [comment]
恩。是的。我刚刚已经okay了

**Comment by edagarli** [comment]
不过启动的时候出现了这个问题，插件不是默认集成的吗？

nginx: [error] [lua] orange.lua:73: init(): Startup error: ./orange/utils/utils.lua:218: error loading module 'orange.plugins.divide.handler' from file './orange/plugins/divide/handler.lua':
	./orange/plugins/divide/handler.lua:20: unexpected symbol near '<'
