### ISSUE TITLE
无法跳登录问题

### ISSUE THREAD

**Issue by edagarli** [sumory/orange#64]
orange.conf设为true后，登录界面一直进不去,出现502，

 "dashboard": {
        "auth": true,
        "session_secret": "y0ji4pdj61aaf3f11c2e65cd2263d3e7e5",
        "whitelist": [
            "^/auth/login$",
            "^/error/$"
        ]
    },

启动是成功的

justhacker:orange jhp$ sudo orange restart
[INFO] Orange: 0.6.1
[INFO] ngx_lua: 10006
[INFO] nginx: 1011002
[INFO] Lua: LuaJIT 2.1.0-beta2
[INFO] Stop orange...
[INFO] args:
[INFO] 	ngx_conf:/usr/local/orange/conf/nginx.conf
[INFO] 	prefix:/usr/local/orange
[INFO] 	orange_conf:/usr/local/orange/conf/orange.conf
[INFO] args end.
[INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf -s stop
[SUCCESS] Orange stoped.
[INFO] Start orange...
[INFO] args:
[INFO] 	ngx_conf:/usr/local/orange/conf/nginx.conf
[INFO] 	prefix:/usr/local/orange
[INFO] 	orange_conf:/usr/local/orange/conf/orange.conf
[INFO] args end.
[INFO] Start orange command execute.
[INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf
[SUCCESS] Orange started.

看日志出现这个问题

2017/02/17 21:02:00 [error] 52233#0: *25 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:165):3: loop or previous error loading module 'dashboard.main'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:165):3: in function <content_by_lua(nginx.conf:165):1>, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:9999"

**Comment by sumory** [comment]
应该是你本地环境的问题，查下你做了什么变动，比如配置文件，参数之类的。我刚试了下没有这个问题

**Comment by edagarli** [comment]
配置文件没有变动的话，正常运行，但是我直接修改/usr/local/orange/conf/orange.conf里面的
"auth": true后，然后重启后，出现502。感觉与环境无异吧。。。

**Comment by sumory** [comment]
我在两台电脑上都无法复现。你升级到最新的orange v0.6.2和lor v0.3.0再试试？

**Comment by sumory** [comment]
我猜测另一个可能原因是权限或是路径问题，你使用start.sh脚本启动试试，先别用`orange cli`

**Comment by edagarli** [comment]
start.sh脚本我也试过了，直接500 。

因为你前两天不是没有升级嘛，我的版本是orange v0.6.1和lor v0.2.6。

我排查问题，看了另外一个error.log日志，有error，如下：

2017/02/17 21:25:43 [warn] 53895#0: *4 [lua] mysql_store.lua:35: query(): MySQLStore:query empty, sql:select `key`, `value` from meta where `key`=?, context: ngx.timer
2017/02/17 21:25:43 [error] 53895#0: *4 [lua] dao.lua:512: load data of plugin[kvstore] success, context: ngx.timer
2017/02/18 14:18:03 [notice] 78409#0: signal process started

不知道这个error是说明什么？

**Comment by sumory** [comment]
你数据库初始化了吗？

**Comment by edagarli** [comment]
之前是很老版本的sql，我昨天用0.6.1的sql数据库执行跑了一遍。

**Comment by edagarli** [comment]
不过我没有直接把原来表结构全删。是直接用0.6.1语句跑了一般。不知道这样有木有影响。

**Comment by sumory** [comment]
那你SQL应该会跑错吧；可能就是数据问题，你有些初始化数据没放进去。如果你的数据库已经有数据了，就不要随便执行初始化SQL，默认的SQL就是建表和初始化几条数据，你可以diff下sql文件，不要直接覆盖。

**Comment by edagarli** [comment]
这个我试过了。不行。好怪

**Comment by edagarli** [comment]
可能向你说的权限问题，只是日志文件记录信息好少，无法排查

**Comment by sumory** [comment]
别管之前的了，重新安装吧。应该是你本地环境问题，其他使用者没提过你这个问题，我也复现不出来。

**Comment by saighost** [comment]
我遇到了。。。ngixn reload之后莫名其妙的全部500.
报错前在改前端页面。。。

2017/08/23 02:15:12 [error] 15430#15430: *67 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:222):3: loop or previous error loading module 'dashboard.main'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:222):3: in function <content_by_lua(nginx.conf:222):1>, client: 118.81.236.6, server: pp.qichexin.com, request: "GET /pc/wzry/wzpf.html HTTP/1.1", host: "pp.qichexin.com"
