### ISSUE TITLE
version 0.6.3 启动错误module 'orange.orange' not found:

### ISSUE THREAD

**Issue by liuwenru** [sumory/orange#78]
您好，我在搭建orange时，尝试启动时发现如下错误，但是我看了我的当前路径下是存在这个目录的，能提示一下我是那边的环境配合i错误了

[INFO] Orange: 0.6.3
[INFO] ngx_lua: 10007
[INFO] nginx: 1011002
[INFO] Lua: LuaJIT 2.1.0-beta2
[INFO] args:
[INFO]  ngx_conf:/usr/local/orange/conf/nginx.conf
[INFO]  prefix:/usr/local/orange
[INFO]  orange_conf:/usr/local/orange/conf/orange.conf
[INFO] args end.
[INFO] Start orange command execute.
[INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf 
nginx: [error] init_by_lua error: init_by_lua:2: module 'orange.orange' not found:
        no field package.preload['orange.orange']
        no file '../orange/orange.lua'
        no file '/usr/local/lor/orange/orange.lua'
        no file '/opt/lor/orange/orange.lua'
        no file '/opt/openresty/site/lualib/orange/orange.so'
        no file '/opt/openresty/lualib/orange/orange.so'
        no file './orange/orange.so'
        no file '/usr/local/lib/lua/5.1/orange/orange.so'
        no file '/opt/openresty/luajit/lib/lua/5.1/orange/orange.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/opt/openresty/site/lualib/orange.so'
        no file '/opt/openresty/lualib/orange.so'
        no file './orange.so'
        no file '/usr/local/lib/lua/5.1/orange.so'
        no file '/opt/openresty/luajit/lib/lua/5.1/orange.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        init_by_lua:2: in main chunk

**Comment by sumory** [comment]
/usr/local/orange目录是否存在？你怎么安装的？

**Comment by liuwenru** [comment]
目录是存在的，我知道了，，能麻烦您告知一下这货的搜索路径是怎么配置的么，
我现在/usr/local/orange/orange目录下运行orange start的化，提示如下错误
nginx: [error] [lua] orange.lua:73: init(): Startup error: ../orange/store/mysql_db.lua:6: module 'resty.mysql' not found:
        no field package.preload['resty.mysql']
        no file '../resty/mysql.lua'
        no file '/usr/local/lor/resty/mysql.lua'
        no file '/opt/lor/resty/mysql.lua'
        no file '/opt/openresty/site/lualib/resty/mysql.so'
        no file '/opt/openresty/lualib/resty/mysql.so'
        no file './resty/mysql.so'
        no file '/usr/local/lib/lua/5.1/resty/mysql.so'
        no file '/opt/openresty/luajit/lib/lua/5.1/resty/mysql.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/opt/openresty/site/lualib/resty.so'
        no file '/opt/openresty/lualib/resty.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/opt/openresty/luajit/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
我搜索了一下这个库位置，我的resty.mysql是在/opt/openresty/lualib/resty   说白了，我感觉就是这个路径我没有对的上，所以导致他搜索不到的。麻烦请告知我可以在那里配置这个搜索的路径！

**Comment by sumory** [comment]
1. 保证你的OpenResty安装正确
2. 保证lor安装正确
3. 不用到/usr/local/orange下运行orange start 命令
4. 请你一开始不要DIY，先按照make install安装，跑通了再自己折腾路径之类的
5. 想DIY，就先了解lua_package_path，orange的配置在conf/nginx.conf中

**Comment by sumory** [comment]
我本地试用了下，v0.6.3通过`make install`安装然后通过`orange start`命令启动没什么问题

**Comment by sumory** [comment]
#66

**Comment by sumory** [comment]
#66
