### ISSUE TITLE
分流代理时，post参数不支持

### ISSUE THREAD

**Issue by phphappy** [sumory/orange#79]
orange中配置如下：
![qq 20170313174527](https://cloud.githubusercontent.com/assets/2278180/23849068/f88fc408-0814-11e7-80e3-b5ffe5156b9d.png)
post调用
http://10.1.1.243/authz/oauth/token?client_id=ySL8OIcFkpZr9gepM3gX&client_secret=Hhte7DXDaHBZ6do01bwt&grant_type=client_credentials&scope=read
提示：
{
    "error_description": "Missing grant_type parameter value",
    "error": "invalid_request"
}

明明有grant_type这个字段啊

**Comment by sumory** [comment]
PostForm指的是表单里的参数，你用URL提交当然找不到。

**Comment by phphappy** [comment]
我是用post方法提交的，在postparam里面

**Comment by phphappy** [comment]
PostParam ,不是PostForm

**Comment by sumory** [comment]
#76

**Comment by phphappy** [comment]
![post](https://cloud.githubusercontent.com/assets/2278180/23881657/c938c54c-0896-11e7-9f5d-942e548cd285.png)
我是这种请求方式，这种方式是form-data？

**Comment by sumory** [comment]
没用过你这个软件

**Comment by phphappy** [comment]
分流支持post请求么？

**Comment by sumory** [comment]
可以

**Comment by phphappy** [comment]
我这种情况，post请求就不可以。请问什么原因？识别不了postparam

**Comment by sumory** [comment]
对Post类型，目前orange只支持为Content-Type: application/x-www-form-urlencoded的Post请求
