### ISSUE TITLE
Distribution package for orange

### ISSUE THREAD

**Issue by syhily** [sumory/orange#8]
1. [ ] Homebrew formula. (I would like to work on this part.)
2. [ ] Linux RPM distribution.
3. [X] Docker distribution.
4. [ ] Mac pkg distribution.
5. [ ] Luarocks rockspec distribution.

**Comment by syhily** [comment]
@sumory Orange doesn't have a proper command line interface, but this issue need it.

**Comment by sumory** [comment]
`orange` cli is available from v0.5.0

**Comment by syhily** [comment]
Got it, i would make homebrew version available first.
