### ISSUE TITLE
nginx的反向代理对应着orange的哪个插件

### ISSUE THREAD

**Issue by phphappy** [sumory/orange#82]
nginx的反向代理对应着orange的哪个插件？是URL重定向还是WAF插件？

**Comment by sumory** [comment]
分流divide插件

**Comment by phphappy** [comment]
API版本管理用devide,还是rewrite、Redirect?
比如：orange地址为http://10.1.1.1，
接口地址为： http://10.1.1.2/getUser，
在orange上怎么实现访问orange (http://10.1.1.1/v1.0.0/getUser) ,就能指向http://10.1.1.2/getUser这个接口？

**Comment by sumory** [comment]
API版本管理需要你自己制定策略，比如是在header头注入版本号还是请求里(uri、querystring、form表单)携带版本号。

针对你说的这个具体需求，两种方法：
- 为10.1.1.2添加一个upstream，然后使用分流插件，判断uri里的版本号是v1.0.0的时候打到后端的10.1.1.2这个upstream
- 使用redirect插件，这样会多一次客户端跳转

这些具体的使用问题，希望你能先了解清楚Nqinx的基本功能，再来使用Orange会事半功倍。
