### ISSUE TITLE
分流插件，支持request body吗？

### ISSUE THREAD

**Issue by phphappy** [sumory/orange#84]
分流插件，支持request body吗？如果不支持，应该怎么解决？

**Comment by sumory** [comment]
#79 请不要提重复的issue，这个问题你已经提过了

**Comment by phphappy** [comment]
个人水平有限，想依赖orange实现转发，上图的请求类型有两种，一种是body,一种是query。请问能走orange的转发吗？

**Comment by sumory** [comment]
在你之前提的issue里已经给过你答案：

```
对Post类型，目前orange只支持`Content-Type: application/x-www-form-urlencoded`的Post请求
```
目前Orange没有提供`multipart/form-data`,`application/json`,`text/xml`的Post请求解析，所以不能使用`条件判断模块`和`变量提取模块`，但对这些请求做简单的分流等处理是可以的。

至于post请求有哪几种类型(扩展开来，基本的HTTP协议的知识)，它们有什么区别和使用场景，需要你自己搞清楚，这并不是Orange这个项目的范畴，也不应该在这里提issue寻求答案。

**Comment by shengnoah** [comment]
这是一个好问题啊， 但貌似图挂了。

**Comment by phphappy** [comment]
用分流插件配置
orange服务器为：10.1.1.1
当访问http://10.1.1.1/checkToken?access_token=aaaaaaaa;
转到http://10.1.1.2:8080/ele-base-web/api/plat/checkToken?access_token=aaaaaaaa;
但是现在的效果是10.1.1.2那台机器接收不到access_token参数
请问如何配置
![qq 20170313174527](https://cloud.githubusercontent.com/assets/2278180/24579685/8a8d7834-172c-11e7-963c-3bf4cb760c59.png)

**Comment by sumory** [comment]
- 分流插件对应的是Nginx的upstream。upstream是不能这样用的，具体用法请自行google。你需要现在nginx.conf配置一个upstream，然后在Orange分流插件里配上http://${upstream的名称}。
- 你这需求应该用redirect插件更合适吧?

还有，请注意提问时不要在无关issue下提问题。如果你还不注意issue要求和质量，我就不予回答了。

**Comment by phphappy** [comment]
连个配置文档都没有，难道让我们自己猜吗？
