### ISSUE TITLE
Better configuration allocation

### ISSUE THREAD

**Issue by syhily** [sumory/orange#9]
1. [x] Remove file store.
2. [ ] Add PostgreSQL support, pgmoon would be a good choice.
3. [x] Join orange.conf and nginx.conf together, a yml file would be a good chocie, just like `kong`.

**Comment by sumory** [comment]
`orange.conf` and `nginx.conf` will stay separately in the future. no more complexity would be introduced about the configuration now.

**Comment by sumory** [comment]
PostgreSQL support moved to another issue #24
