### ISSUE TITLE
多个插件配置同一个条件的规则匹配优先级顺序是什么？

### ISSUE THREAD

**Issue by zz0412** [sumory/orange#92]
你好：
  多个插件配置同一个条件的规则匹配优先级顺序是什么？

对于/bbbb 路径，要求配置如下：

- 只有192.168.2.100过来的流量重定向到http://www.baidu.com

- 其他ip过来的流量报404错误

 所有选择器均配置“继续后续选择器”。实际测试结果，所有的流量均重定向到http://www.baidu.com

环境如下：
orange:0.6.3
OpenResty:1.11.2.2
lor:0.3.0

**Comment by sumory** [comment]
在URL重定向插件中配置规则，ip是192.168.2.100的流量重定向到http://www.baidu.com
在WAF防火墙插件中配置规则，ip!=192.168.2.100的流量响应404状态码

**Comment by sumory** [comment]
重定向插件执行后才会执行WAF插件

**Comment by zz0412** [comment]
有跳插件优先级的功能么？比如我这种场景，防火墙应该是第一优先级

**Comment by sumory** [comment]
在同一个执行阶段内部是可以调整插件执行优先级的，但跨执行阶段的就不行，因为这个执行阶段是Nginx本身的架构逻辑。
比如重定向插件处在rewrite阶段，WAF插件处在access阶段，Nginx先执行rewrite阶段再执行access阶段。

**Comment by zz0412** [comment]
有类似的插件工作原理的文档么？

**Comment by sumory** [comment]
没有，可以随便找一个插件可以看一遍代码就懂了，原理不复杂。

**Comment by zz0412** [comment]
同样处在access阶段的插件怎么控制几个插件的优先级？

**Comment by sumory** [comment]
每个插件都有一个`PRIORITY`变量来控制优先级，具体请看代码。

**Comment by zz0412** [comment]
WAFHandler.PRIORITY = 2000
DivideHandler.PRIORITY = 2000
值越小，优先级越高？

**Comment by sumory** [comment]
![image](https://cloud.githubusercontent.com/assets/1326893/25079320/edc25efe-236d-11e7-8ad8-751f9d905c65.png)
以上是排序代码，更多细节请参看代码实现。

**Comment by wang-xiaowu** [comment]
> WAFHandler.PRIORITY = 2000 DivideHandler.PRIORITY = 2000 值越小，优先级越高？

值越大，优先级越高
