### ISSUE TITLE
代理插件支持多host配置

### ISSUE THREAD

**Issue by liuwenru** [sumory/orange#98]
您好，我配置好orange后，在页面中查看了代理插件的用法，发现只可以填写一个host地址，且upstream url配置为 `http://后端服务器IP:port/appurl`才可以访问，实际抓包发现服务端发回了302重新定向至后端的服务器的，麻烦请问一下是否是我配置有误还是理解错误，如果我想使用orange做多个host地址的负载均衡和反响代理如何配置，是否有相关的配置说明。谢谢！
![qq 20170421150154](https://cloud.githubusercontent.com/assets/7694194/25266523/0ca46a36-26a4-11e7-98d6-777a183d80df.png)

**Comment by sumory** [comment]
你需要在nginx.conf为你后端服务器配到一个`upstream`，然后使用代理插件将upstream_url配置为http://${你的upstream的名称}。

关于`upstream`的使用方法请自行google nginx相关知识点。
